# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        使用bdm账号查看bd的拜访数
    输入参数：
       "startTime": 开始时间
        "endTime": 结束时间
        "operatorId": Bd id
        "signRecordResultType": 签到类型(签到结果类型valid:有离店打卡时间的有效拜访,lost_follow-up:失访上报数据,not_leave:没有离店打卡记录)
    输出参数：
        无
    前置接口：
        用户登陆；获取私海列表
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from ppApp.api.店铺签到分页列表查询_test import TestCase店铺签到分页列表查询 as 店铺签到分页列表查询


class TestCasebdm查看拜访管理(HttpRunner):
    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "15757113586",
            "session": "${getSession($business,$phone)}",
            "startTime": "${hapentime(0,1)}",
            "endTime": "${hapentime(0,1)}",
            "operatorId": "1489",
            "signRecordResultTypes": ["lost_follow-up"],
        }).export(*["SignShopPageData"])

    teststeps = [
        Step(
            RunTestCase("店铺签到分页列表查询").with_variables(
                **{
                    "operatorIds": "${makeList($operatorId)}",
                    "signRecordResultTypes": "$signRecordResultTypes",
                }
            ).call(店铺签到分页列表查询)
            .export(*["SignShopPageData"])
            .teardown_hook("${sleep_N_secs(1)}")
        ),
    ]


if __name__ == "__main__":
    TestCasebdm查看拜访管理().test_start()
