# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        bd对私海店铺拜访未离店，bdm在拜访管理中验证bd对该店铺拜访，不进行离店打卡
    输入参数：
        "phone": bd手机号，需要有私海店铺
        "shopId": bd私海店铺中可进行拜访的店铺id
        、"signRecordResultType": 签到类型(签到结果类型valid:有离店打卡时间的有效拜访,lost_follow-up:失访上报数据,not_leave:没有离店打卡记录)
    输出参数：
        无
    前置接口：
        无
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from ppApp.业务脚本.私海店铺拜访未离店_test import TestCase私海店铺拜访未离店 as 私海店铺拜访未离店
from yyht.权限管理.拼拼账号管理.业务脚本.根据bd寻找bdm_test import TestCase根据bd寻找bdm as 根据bd寻找bdm
from ppApp.业务脚本.bdm查看拜访管理_test import TestCasebdm查看拜访管理 as bdm查看拜访管理


class TestCase私海店铺拜访未离店(HttpRunner):
    config = Config("testcase description").verify(False).variables(
        **{
            "phone": "15757113586",
            "shopId": "${拼拼公私海店铺生成个未拜访的店铺id($phone,0)}",
            "signRecordResultTypes": ["not_leave"],
        })

    teststeps = [
        Step(
            RunTestCase("私海店铺拜访未离店").call(私海店铺拜访未离店)
            .teardown_hook("${sleep_N_secs(3)}")
        ),
        Step(
            RunTestCase("根据bd信息寻找他的bdm信息").with_variables(
                **{
                    "bdPhone": "$phone",
                }
            ).call(根据bd寻找bdm)
            .export(*["bdId", "bdPhone"])
            .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("bdm查看拜访管理").with_variables(
                **{
                    "phone": "$bdPhone",
                    "operatorId": "$bdId",
                    "signRecordResultTypes": "$signRecordResultTypes",
                }
            ).call(bdm查看拜访管理)
            .export(*["SignShopPageData"])
            .teardown_hook("${assert_contains($SignShopPageData,shopId=intType$shopId)}")
        ),
    ]


if __name__ == "__main__":
    TestCase私海店铺拜访未离店().test_start()
