# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        子任务详情
    输入参数：
        "id": id
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase子任务详情(HttpRunner):

    config = Config("子任务详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "id": "1205641401994201908"
        })

    teststeps = [
        Step(
            RunRequest("/test_t/pinpin/visitTask/subTaskDetail")
            .get("/pinpin/visitTask/subTaskDetail")
            .with_params(**{"id": "$id"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase子任务详情().test_start()
"""
response:
body     : {
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: null",
    "timestamp": 1603952278,
    "signType": null,
    "sign": null,
    "body": {
        "subTaskId": "1205641401994201908",
        "subTaskType": "customize",
        "subTaskName": "tt2",
        "departmentName": "市场",
        "departmentCode": "marketing",
        "createName": "孙超",
        "createTime": "2020-10-27 10:02:20",
        "templateContextJson": "[{\"type\":\"radio\",\"name\":\"单选\",\"options\":{\"required\":false,\"label\":\"\",\"placeholder\":\"\",\"options\":[{\"label\":\"选项1\",\"value\":0},{\"label\":\"选项3\",\"value\":2},{\"label\":\"选项4\",\"value\":4}],\"defaultValue\":\"\"},\"key\":\"radio_1603764122000_46293\"}]",
        "defaultValueJson": null,
        "requiredFlag": null,
        "sortNo": null,
        "flag": null
    }
}

"""