# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        业务审核驳回
    输入参数：
        "operateCostDetailId": 运费单据id
    输出参数：

    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase业务审核驳回(HttpRunner):

    config = Config("业务审核驳回").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "operateCostDetailId": "1198741091140351807"
        })

    teststeps = [
        Step(
            RunRequest("/logis/transBill/operateCost/reject")
            .post("/logis/transBill/operateCost/reject")
            .with_params(
                **{"operateCostDetailId": "$operateCostDetailId", "reason": "驳回"}
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", "操作成功")
        ),
    ]


if __name__ == "__main__":
    TestCase业务审核驳回().test_start()

"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603088429983",
	"timestamp": 1603088429,
	"signType": null,
	"sign": null,
	"body": "操作成功"
}
"""
