# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        新建车队
    输入参数：
        fleetName   车队名称
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新建车队(HttpRunner):

    config = Config("新建车队").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "fleetName": "${createRandomNumber(7)}"
        })

    teststeps = [
        Step(
            RunRequest("/logis/api/mng/driverFleet/add")
            .post("/logis/api/mng/driverFleet/add")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "43",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"fleetName": "$fleetName", "cityCode": "330100"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase新建车队().test_start()
