# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        查看司机详情
    输入参数：
        driverId 司机id
    输出参数：
        bankAccountName", 银行账户名
        "accountStatus"   账号状态
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查看司机详情(HttpRunner):

    config = Config("查看司机详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "driverId": "2764"
        }).export(*["bankAccountName","accountStatus","detailDriverIdStr"])

    teststeps = [
        Step(
            RunRequest("/logis/api/mng/drivers/detail")
            .post("/logis/api/mng/drivers/detail")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "19",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"driverId": "$driverId"}).extract()
                .with_jmespath("body.body.bankAccountName", "bankAccountName")
                .with_jmespath("body.body.accountStatus","accountStatus")
                .with_jmespath("body.body.name", "name")
                .with_jmespath("body.body.id", "detailDriverIdStr")


            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase查看司机详情().test_start()


"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1600395575361",
	"timestamp": 1600395575,
	"signType": null,
	"sign": null,
	"body": {
		"id": "4220",
		"geoCityCode": "330100",
		"name": "郑林",
		"phoneNumber": "13429601754",
		"homeZoneCode": "萧山区",
		"homeAddress": "萧山宁围新盛村",
		"driverType": 1,
		"drivingLicenseURL": null,
		"signDate": null,
		"cooperationStatus": 50,
		"accountStatus": 10,
		"identityNumber": "411527198606251017",
		"vehicleType": 12,
		"licensePlateNumber": "浙AN9K90",
		"vehicleLicenseURL": "http://images.pinpianyi.com/images/face/LOGISTICS_26313b22cf0f4534a14ab276e0744fe5.jpg",
		"urgencyContactName": "",
		"urgencyContactPhoneNumber": "",
		"graphicalPosition": "120.304577,30.203563",
		"serviceManagerId": 331,
		"carrierName": "四城南",
		"driverOwnership": "514",
		"bankName": "招商银行",
		"bankAccountName": "郑林",
		"bankNumber": "6214835715953137",
		"bankProvince": null,
		"bankCity": "杭州",
		"bankAddress": "临平支行",
		"bankAccountType": null,
		"bankIdentityCode": null,
		"identityCardUrl": null,
		"vehiclePhotosUrl": null,
		"logisTraCode": "3310003"
	}
"""