# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        查询承运商详情
    输入参数：
        "id":"1", 承运商id
    输出参数：
        carrierId 承运商id
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查看供应商详情(HttpRunner):

    config = Config("查看供应商详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "id":"1",
        }).export(*["carrierId"])

    teststeps = [
        Step(
            RunRequest("/logis/api/mng/carriers/queryDetail")
            .get("/logis/api/mng/carriers/queryDetail")
            .with_params(**{"id": "$id"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            ).extract().with_jmespath("body.body.carrierId","carrierId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase查看供应商详情().test_start()
