# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        运费管理列表查询
    输入参数：
        无
    输出参数：
        transportationNo 运单号
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查询运费管理(HttpRunner):

    config = Config("查询运费管理").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "transportationNo":""
        }).export(*["transportationNo"])

    teststeps = [
        Step(
            RunRequest("/logis/transBill/basicCost/list")
            .post("/logis/transBill/basicCost/list")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "189",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "pageNum": 1,
                    "pageSize": 500,
                    "startDeliverFinishTime": "",
                    "endDeliverFinishTime": "",
                    "statusList": [],
                    "driverTypeList": [],
                    "transportationNo":"$transportationNo",
                    "isFee": None,
                    "cityCode": "330100",
                }
            ).extract()
                .with_jmespath("body.body.pageData[0].transportationNo","transportationNo")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase查询运费管理().test_start()


"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603014247682",
	"timestamp": 1603014247,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 500,
		"pageCount": 1,
		"totalSize": 1,
		"pageData": [{
			"id": "1110192781989061575",
			"transportationNo": "2010091190255931143781146",
			"driverId": "68",
			"driverName": "周兰涛1111",
			"driverPhone": "13738113393",
			"vehicleName": "金杯",
			"licensePlateNumber": "浙AK8M05",
			"driverType": 1,
			"status": 10,
			"deliverFinishTime": "2020-10-09 14:40",
			"basicExpense": 50452,
			"otherExpense": 0,
			"pickupPointNum": 1,
			"deliveryPointNum": 1,
			"goodsNum": 10
		}]
	}
}
"""