# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：

    输入参数：

    输出参数：

    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase售货分析(HttpRunner):

    config = Config("售货分析").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-supplier-api/supplierOrder/saleStatistics")
            .get(
                "https://gyapi.dev2.pinpianyi.cn/ppy-supplier-api/supplierOrder/saleStatistics"
            )
            .with_params(**{"type": "1"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase售货分析().test_start()
