# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        获取已有供应品牌列表
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env


class TestCase已有供应品牌列表(HttpRunner):

    config = Config("已有供应品牌列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "44548290f76a4f4bb8b1f75e88ff548b",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-supplier-api/supplier/supplierGoodsBrandList")
            .get(
                "/supplier/supplierGoodsBrandList"
            )
            .with_params(**{"status": "1"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase已有供应品牌列表().test_start()
