# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import random


class TestCase新增商品(HttpRunner):

    config = Config("新增商品").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "gysht",
            "session": "91acf33e3cbd4f34989af86cc154a1b8",
            "barCode": random.randint(111111111, 9999999999),
            "name": "喝酒啊111",
            "brandId": 28,
        })

    teststeps = [
        Step(
            RunRequest("/ppy-supplier-api/goods/apply/add")
            .post("/goods/apply/add")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "733",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "barCode": "$barCode",
                    "barCodeImageUrl": "http://images.alpha.pinpianyi.cn/images/goods/barCoded0188bd327ce442295fd011a97851414.png",
                    "goodsCapacity": 2,
                    "goodsPacknum": 2,
                    "weight": 2,
                    "scatteredPrice": 2,
                    "retailPrice": 2,
                    "guaranteePeriod": 2,
                    "brandId": "$brandId",
                    "goodsCapacityUnit": "ml",
                    "goodsPacketUnit": "包",
                    "goodsPacknumUnit": "包",
                    "name": "$name",
                    "mainImageUrl": "http://images.alpha.pinpianyi.cn/images/library/d853186eb7c441abbb24fef9b9472f46.png",
                    "detailImageUrls": [
                        "http://images.alpha.pinpianyi.cn/images/library/b5042e94dee842e5909a03d03b9c32a2.jpg"
                    ],
                    "storageMethod": "2",
                    "guaranteePeriodUnit": "年",
                    "single": 2,
                    "specificationDesc": "1ml/包",
                    "backstageCategoryId": 1136,
                    "specialty": 0,
                    "isImport": 0,
                    "lwh": "1x1x1",
                    "theoryVolume": 1,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增商品().test_start()
