# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        用户登陆，获取session
    输入参数：
        "user": 供应商登陆用户名
        "pass": 供应商登陆密码
    输出参数：
        "session":登陆凭证
    前置接口：
        无
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env

class TestCase用户登陆(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "gysht",
            "user": "18042466654",
            "pass": "9a46296d3305d019a4f60b2cead2a956",
        }
    )

    teststeps = [
        Step(
            RunRequest("获取session")
            .post("/login/login")
            .with_params(
                **{"user": "$user", "pwd": "$pass"}
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Accept": "application/json, text/plain, */*",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_data("")
            .extract()
            .with_jmespath("body.body.sessionId", "session")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            ),

    ]


if __name__ == "__main__":
    TestCase用户登陆().test_start()
"""
response:
body     : {
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: 1601305863040",
    "timestamp": 1601305863,
    "signType": null,
    "sign": null,
    "body": {
        "sessionId": "44548290f76a4f4bb8b1f75e88ff548b",
        "key": "a555eef3dc804525abdee7727618ea37",
        "ifCloudStorage": 0,
        "cloudType": 0,
        "roleId": 0,
        "roleText": "主管",
        "loginUser": "李良东",
        "level": "子账号",
        "phone": "18042466654",
        "supplierName": "玉彬酒水",
        "active": null
    }
}
"""