# -*- coding: utf-8 -*-
# @Time : 2020/9/15 17:36
# @Author : 郑和
# @File : 新增会员红包_test.py

# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        为商户钱包充钱
    输入参数：
        "phone": 运营后台登陆账号,
        "pass": 运营后台登陆密码
        "cityCode": 运营后台登陆选择城市

        "tradeAmount": 充值数额
        "userphone": 被充值的账号
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from yyht.营销中心.api.新增会员红包页面初始化信息_test import TestCase新增会员红包页面初始化信息 as 新增会员红包页面初始化信息
from yyht.营销中心.api.根据红包id查询红包详情_test import TestCase根据红包Id查询红包详情 as 根据红包Id查询红包详情
from yyht.营销中心.api.新增专享红包_test import TestCase新增专享红包 as 新增专享红包



class TestCase新增专享红包(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "pass": "123456",



        })

    teststeps = [
        Step(
            RunTestCase("新增会员红包页面初始化信息").call(新增会员红包页面初始化信息).export(*["redPacketId"])
            .teardown_hook("${sleep_N_secs(2)}")
        ),
        Step(
            RunTestCase("根据红包id查询红包详情").call(根据红包Id查询红包详情).teardown_hook("${sleep_N_secs(2)}")
        ),
        Step(
            RunTestCase("新增专享红包").call(新增专享红包).teardown_hook("${sleep_N_secs(2)}")
        ),
    ]


if __name__ == "__main__":
    TestCase新增专享红包().test_start()
