# -*- coding: utf-8 -*-
# @Time : 2020/9/15 17:36 
# @Author : 郑和
# @File : 新增会员红包_test.py

# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        为商户钱包充钱
    输入参数：
        "phone": 运营后台登陆账号,
        "pass": 运营后台登陆密码
        "cityCode": 运营后台登陆选择城市

        "tradeAmount": 充值数额
        "userphone": 被充值的账号
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from yyht.营销中心.api.新增会员红包_test import TestCase新增会员红包 as 新增会员红包
from yyht.营销中心.api.红包列表_test import TestCase红包列表 as 红包列表
from yyht.营销中心.api.获取红包审核信息详情_test import TestCase获取红包审核信息详情 as 获取红包审核信息
from yyht.营销中心.api.审核红包_test import TestCase审核红包 as 审核红包


class TestCase新增会员红包(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "availableStartTime": "2020-09-30 00:00:00",
            "availableEndTime": "2020-10-30 00:00:00",
            "packetName": "会员红包6块6",



        })

    teststeps = [
        Step(
            RunTestCase("新增会员红包").call(新增会员红包).teardown_hook("${sleep_N_secs(2)}")
        ),
        Step(
            RunTestCase("红包列表").call(红包列表).export(*["packetId"])
            .teardown_hook("${sleep_N_secs(2)}")
        ),
        Step(
            RunTestCase("获取红包审核信息").call(获取红包审核信息).teardown_hook("${sleep_N_secs(2)}")
        ),
        Step(
            RunTestCase("审核红包").call(审核红包).teardown_hook("${sleep_N_secs(2)}")
        ),
    ]


if __name__ == "__main__":
    TestCase新增会员红包().test_start()
