#! /usr/bin/env python
#-*- coding:utf-8 -*-

#author:bingo
# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        用户对指定商品下单，使用账户余额付款
    输入参数：
        "phone": 登陆手机号
        "goodsId": 商品id
        "goodsNu": 下单商品数量
    输出参数：
        无
    前置接口：
        验证码登陆
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from ppyApp.api.帐号注册_test import TestCase帐号注册 as 帐号注册
from ppyApp.api.重置密码_test import TestCase重置密码 as 设置密码和邀请人
from ppyApp.api.查询审核信息_test import TestCase查询审核信息 as 查询审核信息
from ppyApp.api.首页BD业务员推送消息提醒_test import TestCase首页Bd业务员推送消息提醒 as 首页Bd业务员推送消息提醒
from ppyApp.api.创建用户资料_test import TestCase创建用户资料 as 创建用户资料
from ppyApp.api.上传用户头像_test import TestCase上传用户头像 as 上传用户头像
from ppyApp.api.发送验证码_test import TestCase发送验证码 as 发送验证码
from ppyApp.api.提交设备信息_test import TestCase提交设备信息 as 提交设备信息


class TestCase新用户注册(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "account": "13366666663",
            "shareCode": "706",
            "newPassword": "SS123456",
            "longitude": 114.523609,
            "latitude": 30.37887,
            "landmarkName": "这是一个测试地址，请不要信",
            "shopAddress": "这是一个测试地址，请不要信",
            "shopName": "test1019",
        }
    )

    teststeps = [
        Step(
            RunTestCase("发送验证码").with_variables(
                **{
                    "phone": "$account",
                }
            ).call(发送验证码)
        ),
        Step(
            RunTestCase("帐号注册").call(帐号注册).export(*["token"])
                .teardown_hook("${sleep_N_secs(3)}")
        ),
        Step(
            RunTestCase("设置密码和邀请人").call(设置密码和邀请人)
                .export(*["token"]).teardown_hook("${sleep_N_secs(4)}")
        ),
        Step(
            RunTestCase("查询审核信息").call(查询审核信息)
                .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("首页Bd业务员推送消息提醒").call(首页Bd业务员推送消息提醒)
                .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("上传用户头像").call(上传用户头像)
                .export(*["headerPics"]).teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("创建用户资料").with_variables(
                **{
                    "contactUserName": "$shopName",
                    "shopName": "$shopName",
                }
            ).call(创建用户资料).teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("提交设备信息").call(提交设备信息)
                .teardown_hook("${sleep_N_secs(1)}")
        ),

    ]


if __name__ == "__main__":
    TestCase新用户注册().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603092265,
	"signType": null,
	"sign": null,
	"body": {
		"shopId": "343410",
		"account": "13366666666",
		"shopName": "test1019",
		"contactUserName": "test1019",
		"contactMobilePhone": "13366666666",
		"headerPics": "images/common/439d924c4981421ebaac2a23fb689e29.jpg",
		"cityCode": "0",
		"cityName": null,
		"zoneCode": "420115",
		"zoneName": null,
		"streetCode": "420115088",
		"streetName": null,
		"shopType": "00",
		"shopTypeText": null,
		"shopAddress": "可口可乐的广告",
		"longitude": 114.523609,
		"latitude": 30.37887,
		"statusCode": 0,
		"message": null,
		"errorUrl": null,
		"iconUrl": null,
		"labelColor": null,
		"memberLevel": null,
		"landmarkName": "武昌县龙泉乡福利小学",
		"landmarkAddress": "",
		"businessLicense": null,
		"bdId": 706,
		"bdName": null,
		"bdPhone": null
	}
}
"""