# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        运单列表
    输入参数：
        "orderNo": 订单编号
        "transOrderId": 运单编号
        "driverName": 配送员
        "driverId": 配送员ID
        "driverPhoneNumber": 司机电话
        "id": 运单ID
        "startTime": 起始时间
        "endTime": 截止时间
        "plannedStartTime": 计划配送起始时间
        "plannedEndTime": 计划配送截止时间
        "transOrderStatus": 运单状态
        "sortRule": 排序规则
        "type": 操作记录
        "driverTypeList": 司机类型状态码 1众包司机、20供应商司机、40承运商、50员工司机
        "zoneCodeList": 物流商圈编码
    输出参数：
        "transOrderId":运单编号
        "phoneNumber":司机联系电话
    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env


class TestCase运单列表(HttpRunner):

    config = Config("运单列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "pd",
            "session": "${getSession($business)}",
            "transOrderId": "",
            "orderNo": None,
            "driverName": None,
            "driverId": None,
            "driverPhoneNumber": None,
            "id": None,
            "startTime": None,
            "endTime": None,
            "pageNum": 1,
            "plannedStartTime": "",
            "plannedEndTime": "",
            "pageSize": 10,
            "transOrderStatus": "",
            "sortRule": "101",
            "type": None,
            "driverTypeList": None,
            "zoneCodeList": None,
        }).export(*["transOrderId", "phoneNumber"])

    teststeps = [
        Step(
            RunRequest("/logis/mng/transportationOrder/list")
            .post("/logis/mng/transportationOrder/list")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "376",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "cityCode": env.cityCode,
                    "transOrderId": "$transOrderId",
                    "orderNo": "$orderNo",
                    "driverName": "$driverName",
                    "driverId": "$driverId",
                    "driverPhoneNumber": "$driverPhoneNumber",
                    "id": "$id",
                    "startTime": "$startTime",
                    "endTime": "$endTime",
                    "pageNum": 1,
                    "plannedStartTime": "$plannedStartTime",
                    "plannedEndTime": "$plannedEndTime",
                    "pageSize": 10,
                    "transOrderStatus": "$transOrderStatus",
                    "sortRule": "$sortRule",
                    "type": "$type",
                    "driverTypeList": "$driverTypeList",
                    "zoneCodeList": "$zoneCodeList",
                }
            ).extract()
            .with_jmespath("body.body.pageData[0].id","transOrderId")
            .with_jmespath("body.body.pageData[0].phoneNumber", "phoneNumber")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase运单列表().test_start()
"""
response:
{
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: 1598422503397",
	"timestamp": 1598422504,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 1,
		"totalSize": 2,
		"pageData": [{
			"id": "1152140501313951940",
			"displayId": "2008261152140501313951940",
			"driverName": "滕坤",
			"phoneNumber": "15736950621",
			"licensePlateNumber": "浙A89811",
			"orderNum": 1,
			"status": 600,
			"expectedIncome": "42.48",
			"settleIncome": null,
			"startTime": null,
			"deliverFinishTime": null,
			"thumbnailURL": null,
			"operationLogs": null,
			"createTime": "2020-08-26T03:15:18.000+0000",
			"receiptTime": null,
			"planningMileage": "16225",
			"driverLocationVO": null,
			"driverId": 38076,
			"vehicleType": 13,
			"plannedStartTime": "2020-08-26T03:00:00.000+0000",
			"goodsNum": 4,
			"suppliers": "拼便宜供应链(自备仓)",
			"volumeRate": 10.04,
			"pickupPointAmount": 1,
			"supplierList": ["拼便宜供应链(自备仓)"],
			"zoneCode": "3310001"
		},]
	}
}
"""