# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        对指定运单进行运单生效操作
    输入参数：
        "transOrderId": 运单编号
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase



class TestCase运单生效(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "transOrderId": "1140902081197681368"
        })

    teststeps = [
        Step(
            RunRequest("运单生效")
            .post(
                "/logis/mng/transportationOrder/effect"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "44",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json({"transOrderIdList": ["$transOrderId"]})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase运单生效().test_start()

"""
request:
{
	"transOrderIdList": ["1139206991306161775"]
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597124836302",
	"timestamp": 1597124837,
	"signType": null,
	"sign": null,
	"body": ""
}
"""