# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        为订单派单，且使订单生效（只对订单中有一种商品生效，且供应商列表中第一个供应商可以满足供货，其他情况暂时未考虑）
    输入参数：
        "phone": 运营后台登陆账号
        "pass": 运营后台登陆密码
        "cityCode": 城市编号
        "orderNo": 订单号
    输出参数：
        无
    前置接口：
        无
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from yyht.订单中心.api.人工拆单页面订单详情_test import TestCase人工拆单页面订单详情 as 人工拆单页面订单详情
from yyht.运营后台供应商api.api.查询库存_test import TestCase查询库存 as 查询库存
from yyht.订单中心.api.人工派单_test import TestCase人工派单 as 人工派单
from yyht.订单中心.api.订单派单生效_test import TestCase订单派单生效 as 订单派单生效


class TestCase派单(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "${getSession($business)}",
            "orderNo": "2020082614205314713539"
        })

    teststeps = [
        Step(
            RunTestCase("人工拆单页面订单详情").call(人工拆单页面订单详情)
                .export(*["goodsId", "goodsNum"])
                .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("查询库存").call(查询库存)
                .export(*["supplierId", "storageId", "virtualStorageId"])
                .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("人工派单").call(人工派单).teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("订单派单生效").call(订单派单生效).teardown_hook("${sleep_N_secs(1)}")
        ),
    ]


if __name__ == "__main__":
    TestCase派单().test_start()
