# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        登陆用户验证
    输入参数：
        "mobile": 用户手机号
        "passwd": 用户密码
        "code": 验证码
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env

class TestCase登陆用户验证(HttpRunner):

    config = Config("登陆用户验证").verify(False).base_url("${testEnv($business,newweb)}").variables(
        **{
            "business": "yyht",
            "session": "",
            "mobile": env.phone,
            "passwd": env.password,
            "code": "892939"
        })

    teststeps = [
        Step(
            RunRequest("/API/ppy-auth/api/login/loginCheckUser")
            .post("/ppy-auth/api/login/loginCheckUser")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "61",
                    "sessionId": "$session",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {"mobile": "$mobile", "passwd": "$passwd", "code": "$code"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase登陆用户验证().test_start()
