# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        战区添加成员
    输入参数：
        "regionName": 战区名称
        "phone": bd手机号码
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from yyht.商圈管理.便利店战区管理.api.列表展示_test import TestCase列表展示 as 查找战队
from yyht.权限管理.拼拼账号管理.api.bd人员列表查询_test import TestCaseBd人员列表查询 as 查找bd
from yyht.商圈管理.便利店战区管理.api.添加战区人员信息_test import TestCase添加战区Bd关系 as 添加战区人员


class TestCase战区添加成员(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "regionName": "aaaa",
            "phone": "13868018217",

        })

    teststeps = [
        Step(
            RunTestCase("查找战队").call(查找战队).export(*["regionId"])
        ),
        Step(
            RunTestCase("查找bd").call(查找bd).export(*["bdId"])
                .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("添加战区人员").call(添加战区人员)
        ),
    ]


if __name__ == "__main__":
    TestCase战区添加成员().test_start()
