# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        获取战区内有效经纬度
    输入参数：
        "regionName": 战区名称
        "disable": 战区是否可用，0-可用，1-不可用
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from yyht.商圈管理.便利店战区管理.api.列表展示_test import TestCase列表展示 as 查找战队
from yyht.商圈管理.便利店战区管理.api.根据id查询战区_test import TestCase根据Id查询战区 as 根据Id查询战区

class TestCase获取战区内有效经纬度(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "regionName": "火炮战队",
            "disable": 0,
        })

    teststeps = [
        Step(
            RunTestCase("查找战队").call(查找战队)
                .export(*["regionId"]).teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunTestCase("根据Id查询战区").call(根据Id查询战区)
                .export(*["regionPointsList"])
                .teardown_hook("${makeGoodPoint($regionPointsList)}")
                .teardown_hook("${sleep_N_secs(1)}")
        ),
    ]


if __name__ == "__main__":
    TestCase获取战区内有效经纬度().test_start()
