# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase标签列表(HttpRunner):

    config = Config("标签列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "name": "上门收款",
        }).export(*["name","disabled","categoryCode","id"])

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-op-api/label/query/page")
            .post("/ppy-op-api/label/query/page")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "67",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "categoryCode": "",
                    "pageNum": 1,
                    "pageSize": 10,
                    "name": "$name",
                }
            ).extract()
                .with_jmespath("body.body.pageData[0].id", "id")
                .with_jmespath("body.body.pageData[0].name","name")
                .with_jmespath("body.body.pageData[0].disabled", "disabled")
                .with_jmespath("body.body.pageData[0].categoryCode", "categoryCode")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase标签列表().test_start()

"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603109434620",
	"timestamp": 1603109434,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 1,
		"totalSize": 1,
		"pageData": [{
			"id": 65,
			"name": "上门收款",
			"code": "2096",
			"categoryCode": "002",
			"categoryName": "订单标签",
			"disabled": 1,
			"frontEndShow": false,
			"createTime": "2018-01-26 17:14"
		}]
	}
}
"""