# Generated by Django 3.2.12 on 2022-04-30 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.IntegerField(choices=[(0, 'times'), (1, 'duration')])),
                ('source', models.TextField(default=None, null=True)),
                ('limit', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(default=None, null=True)),
                ('lic', models.CharField(max_length=32)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('firm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_auth.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('done', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('temp_dest_path', models.CharField(default='', max_length=100)),
                ('log_path', models.CharField(default='', max_length=100)),
                ('temp_name', models.CharField(default='', max_length=100)),
                ('create_firm', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='do_auth.firm')),
                ('create_manager', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SDKinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MD5', models.TextField(default='')),
                ('is_del', models.BooleanField(default=False)),
                ('project', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='do_auth.project')),
            ],
        ),
        migrations.CreateModel(
            name='Lsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsource_list', to='do_auth.licence')),
            ],
        ),
    ]
