# Generated by Django 3.2.12 on 2022-04-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.IntegerField(choices=[(0, 'times'), (1, 'duration')])),
                ('source', models.TextField(default=None, null=True)),
                ('limit', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(default=None, null=True)),
                ('lic', models.CharField(max_length=32)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('firm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_auth.firm')),
            ],
        ),
    ]
