# Generated by Django 3.2.12 on 2022-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_auth', '0002_auto_20220430_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licence',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
