# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        查看参数配置列表
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase参数配置列表查看(HttpRunner):

    config = Config("参数配置列表查看").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        }).export(*["id","dataDesc","dataValue","cityCode"])

    teststeps = [
        Step(
            RunRequest("/logis/support/ctmsConfig/list")
            .post("https://webapi.test.pinpianyi.cn/logis/support/ctmsConfig/list")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "43",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"cityCode": "330100", "dataCode": "", "id": ""}).extract()
                .with_jmespath("body.body[0].id", "id")
                .with_jmespath("body.body[0].dataDesc","dataDesc")
                .with_jmespath("body.body[0].dataValue", "dataValue")
                .with_jmespath("body.body[0].cityCode", "cityCode")

            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase参数配置列表查看().test_start()


"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603092145708",
	"timestamp": 1603092145,
	"signType": null,
	"sign": null,
	"body": [{
		"id": 560,
		"cityCode": "330100",
		"dataCode": 5,
		"dataValue": "15",
		"dataDesc": "司机使用app间断预警值（单位min）",
		"dataType": 1
	}, {
		"id": 563,
		"cityCode": "330100",
		"dataCode": 80,
		"dataValue": "15",
		"dataDesc": "店铺停留时间（单位：分钟）",
		"dataType": 1
	}, {
		"id": 566,
		"cityCode": "330100",
		"dataCode": 75,
		"dataValue": "25",
		"dataDesc": "供应商停留时间(单位：分钟)",
		"dataType": 1
	}, {
		"id": 569,
		"cityCode": "330100",
		"dataCode": 10,
		"dataValue": "08:30:00",
		"dataDesc": "一派：首取完成时间",
		"dataType": 0
	}, {
		"id": 572,
		"cityCode": "330100",
		"dataCode": 15,
		"dataValue": "12:00:00",
		"dataDesc": "一派：取货完成时间",
		"dataType": 0
	}, {
		"id": 575,
		"cityCode": "330100",
		"dataCode": 20,
		"dataValue": "16:00:00",
		"dataDesc": "一派：送货完成时间",
		"dataType": 0
	}, {
		"id": 578,
		"cityCode": "330100",
		"dataCode": 25,
		"dataValue": "15:00:00",
		"dataDesc": "二派：首取完成时间",
		"dataType": 0
	}, {
		"id": 581,
		"cityCode": "330100",
		"dataCode": 30,
		"dataValue": "18:00:00",
		"dataDesc": "二派：取货完成时间",
		"dataType": 0
	}, {
		"id": 584,
		"cityCode": "330100",
		"dataCode": 35,
		"dataValue": "22:00:00",
		"dataDesc": "二派：送货完成时间",
		"dataType": 0
	}, {
		"id": 587,
		"cityCode": "330100",
		"dataCode": 40,
		"dataValue": "13:00:00",
		"dataDesc": "半日达：首取完成时间",
		"dataType": 0
	}, {
		"id": 590,
		"cityCode": "330100",
		"dataCode": 45,
		"dataValue": "16:00:00",
		"dataDesc": "半日达：取货完成时间",
		"dataType": 0
	}, {
		"id": 593,
		"cityCode": "330100",
		"dataCode": 50,
		"dataValue": "20:00:00",
		"dataDesc": "半日达：送货完成时间",
		"dataType": 0
	}, {
		"id": 596,
		"cityCode": "330100",
		"dataCode": 55,
		"dataValue": "0.8",
		"dataDesc": "运力预紧设定值",
		"dataType": 3
	}, {
		"id": 599,
		"cityCode": "330100",
		"dataCode": 60,
		"dataValue": "2",
		"dataDesc": "代收现金需回款跟进时间",
		"dataType": 1
	}, {
		"id": 602,
		"cityCode": "330100",
		"dataCode": 65,
		"dataValue": "0.05",
		"dataDesc": "运单费率异常标准值",
		"dataType": 3
	}, {
		"id": 605,
		"cityCode": "330100",
		"dataCode": 70,
		"dataValue": "0.8",
		"dataDesc": "装载低于异常设定值",
		"dataType": 3
	}, {
		"id": 608,
		"cityCode": "330100",
		"dataCode": 85,
		"dataValue": "30",
		"dataDesc": "司机运单配送间隔时间限制(单位：分钟)",
		"dataType": 1
	}]
}
"""
