# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取计价表信息(HttpRunner):

    config = Config("获取计价表信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "freightRulesId": "24"
        }).export(*["basicCharge", "id"])

    teststeps = [
        Step(
            RunRequest("/logis/api/mng/calculation/detail")
            .get("https://webapi.test.pinpianyi.cn/logis/api/mng/calculation/detail")
            .with_params(**{"freightRulesId": "$freightRulesId"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            ).extract()
                .with_jmespath("body.body.basicCharge", "basicCharge")
                .with_jmespath("body.body.id", "id")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取计价表信息().test_start()
"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603096283803",
	"timestamp": 1603096283,
	"signType": null,
	"sign": null,
	"body": {
		"id": "1198962801147351544",
		"cityCode": "330100",
		"driverType": 1,
		"objId": "3310001",
		"vehicleType": 11,
		"basicCharge": 1201100,
		"minimumCharge": 0,
		"sortType": 2,
		"mileageType": 2,
		"loadType": 2,
		"logisticsCalculationDetailVOList": [{
			"id": "1198962801147451577",
			"calculationRulesId": "1198962801147351544",
			"rulesType": 3,
			"unitPrice": 0,
			"startRules": 0,
			"startPrice": 0,
			"minValue": null,
			"maxValue": null
		}, {
			"id": "1198962801147451582",
			"calculationRulesId": "1198962801147351544",
			"rulesType": 4,
			"unitPrice": 0,
			"startRules": 0,
			"startPrice": 0,
			"minValue": null,
			"maxValue": null
		}, {
			"id": "1198962801147451603",
			"calculationRulesId": "1198962801147351544",
			"rulesType": 9,
			"unitPrice": 0,
			"startRules": 0,
			"startPrice": 0,
			"minValue": null,
			"maxValue": null
		}, {
			"id": "1198962801147451591",
			"calculationRulesId": "1198962801147351544",
			"rulesType": 10,
			"unitPrice": 1000,
			"startRules": 0,
			"startPrice": 0,
			"minValue": 1000,
			"maxValue": 10000
		}, {
			"id": "1198962801147451593",
			"calculationRulesId": "1198962801147351544",
			"rulesType": 11,
			"unitPrice": 5000,
			"startRules": 0,
			"startPrice": 0,
			"minValue": null,
			"maxValue": null
		}]
	}
}
"""