# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase送货单打印详情(HttpRunner):

    config = Config("送货单打印详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "transOrderId": "1195424901146701649"
        }).export(*["driverName"])

    teststeps = [
        Step(
            RunRequest("/test_t/logis/mng/deliveryOrder/listDeliveryOrder")
            .post(
                "/logis/mng/deliveryOrder/listDeliveryOrder"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "38",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"transOrderId": "$transOrderId"})
                .extract().with_jmespath("body.body[0].driverName", "driverName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase送货单打印详情().test_start()
"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603177236337",
	"timestamp": 1603177236,
	"signType": null,
	"sign": null,
	"body": [{
		"deliveryOrderId": "1195424901146741395",
		"driverName": "周兰涛1111",
		"phoneNumber": "13738113393",
		"licensePlateNumber": "浙AK8M05",
		"shopName": "郑小和测试",
		"goodsKindTotal": 1,
		"goodsTotal": 2,
		"plannedStartTime": "2020-10-15 14:14:00",
		"printStatus": 1,
		"status": 0,
		"expectedIncome": null,
		"zoneCode": "3310003"
	}]
}
"""