# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        用户登陆，获取session
    输入参数：
        "phone": 登陆用户名,
        "pwd": 登陆密码,
    输出参数：
        "session":登陆凭证
        "key":公钥key
    前置接口：
        无
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase用户登陆(HttpRunner):

    config = Config("用户登陆").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "phone": "17629262213",
            "pwd": "681851b4cddd9c4f1d5742a7f2da9ce7",
        }
    ).export(*["session", "key"])

    teststeps = [
        Step(
            RunRequest("/ppy-cs-api/user/login")
            .post("/ppy-cs-api/user/login")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "73",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {"phone": "$phone", "pwd": "$pwd"}
            ).extract()
            .with_jmespath("body.body.sessionId","session")
            .with_jmespath("body.body.key","key")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase用户登陆().test_start()

    """
    {
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1598335625776",
	"timestamp": 1598335625,
	"signType": null,
	"sign": null,
	"body": {
		"sessionId": "b955efc8a8774653a77cd933b4df912b",
		"key": "15e1b7700cdf4f9daafc30af69f8c4e9"
	}
}
    """
