# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        获取已登录用户的信息
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取已登录用户的信息(HttpRunner):

    config = Config("获取已登录用户的信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-cs-api/user/getLoginedUserInfo")
            .get("/ppy-cs-api/user/getLoginedUserInfo")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取已登录用户的信息().test_start()
