# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        获取用户信息列表
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取用户信息列表(HttpRunner):

    config = Config("获取用户信息列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-cs-api/user/getEnabledUserList")
            .get("/ppy-cs-api/user/getEnabledUserList")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取用户信息列表().test_start()

"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1598335631719",
	"timestamp": 1598335631,
	"signType": null,
	"sign": null,
	"body": [{
		"id": 1,
		"name": "诸葛可环",
		"phone": "15158070039",
		"createTime": "2018-02-06 10:52:12",
		"status": 1
	}, {
		"id": 3,
		"name": "余涛",
		"phone": "18758207746",
		"createTime": "2018-02-06 12:12:18",
		"status": 1
	}, {
		"id": 4,
		"name": "徐明月",
		"phone": "18662751482",
		"createTime": "2018-02-06 12:12:52",
		"status": 1
	}, {
		"id": 8,
		"name": "吴志刚",
		"phone": "18158139325",
		"createTime": "2018-02-06 14:26:54",
		"status": 1
	}, {
		"id": 11,
		"name": "蒙淮",
		"phone": "17681888373",
		"createTime": "2018-04-07 20:07:59",
		"status": 1
	}, {
		"id": 12,
		"name": "刘帅",
		"phone": "18170878859",
		"createTime": "2018-04-08 13:33:10",
		"status": 1
	}, {
		"id": 13,
		"name": "崔晓洁",
		"phone": "17752241194",
		"createTime": "2018-04-08 13:33:51",
		"status": 1
	}, {
		"id": 19,
		"name": "马娜娜",
		"phone": "15858101828",
		"createTime": "2018-05-28 09:51:14",
		"status": 1
	}, {
		"id": 26,
		"name": "程双",
		"phone": "15155517679",
		"createTime": "2018-06-26 11:55:51",
		"status": 1
	}, {
		"id": 31,
		"name": "徐明月",
		"phone": "16657111236",
		"createTime": "2018-07-16 16:00:03",
		"status": 1
	}, {
		"id": 34,
		"name": "吴树校",
		"phone": "18859102760",
		"createTime": "2018-07-19 12:20:14",
		"status": 1
	}, {
		"id": 40,
		"name": "王敏",
		"phone": "18258108303",
		"createTime": "2018-07-23 15:24:37",
		"status": 1
	}, {
		"id": 45,
		"name": "李孝国",
		"phone": "17629262213",
		"createTime": "2018-08-03 11:37:27",
		"status": 1
	}, {
		"id": 56,
		"name": "邓虹雨",
		"phone": "13065710755",
		"createTime": "2018-12-17 10:09:45",
		"status": 1
	}, {
		"id": 67,
		"name": "蔡斌强",
		"phone": "18767105442",
		"createTime": "2019-04-13 10:15:44",
		"status": 1
	}, {
		"id": 73,
		"name": "顾若鸿",
		"phone": "18658838370",
		"createTime": "2019-04-22 15:21:16",
		"status": 1
	}, {
		"id": 76,
		"name": "郑小和",
		"phone": "15105599965",
		"createTime": "2019-05-13 11:46:48",
		"status": 1
	}, {
		"id": 91,
		"name": "邹彬帅",
		"phone": "17694297496",
		"createTime": "2019-07-11 11:39:54",
		"status": 1
	}, {
		"id": 97,
		"name": "党玉龙",
		"phone": "15924163659",
		"createTime": "2019-07-18 11:06:32",
		"status": 1
	}, {
		"id": 103,
		"name": "张征",
		"phone": "15606711563",
		"createTime": "2019-08-14 18:42:32",
		"status": 1
	}, {
		"id": 109,
		"name": "张道祥",
		"phone": "18551863337",
		"createTime": "2019-12-06 17:51:22",
		"status": 1
	}, {
		"id": 118,
		"name": "俞丹萍",
		"phone": "18158525818",
		"createTime": "2020-03-05 09:14:45",
		"status": 1
	}, {
		"id": 121,
		"name": "沈鸿纯",
		"phone": "18457304949",
		"createTime": "2020-03-05 09:14:59",
		"status": 1
	}, {
		"id": 124,
		"name": "黄坐建",
		"phone": "18958798323",
		"createTime": "2020-03-06 10:57:32",
		"status": 1
	}, {
		"id": 130,
		"name": "张煜冲",
		"phone": "15858182806",
		"createTime": "2020-03-10 10:19:35",
		"status": 1
	}, {
		"id": 133,
		"name": "黄翔",
		"phone": "17317467494",
		"createTime": "2020-03-30 13:33:41",
		"status": 1
	}, {
		"id": 136,
		"name": "徐亚坤",
		"phone": "13175039501",
		"createTime": "2020-04-01 10:59:19",
		"status": 1
	}, {
		"id": 139,
		"name": "胡俊杰",
		"phone": "18657627631",
		"createTime": "2020-05-14 13:34:44",
		"status": 1
	}, {
		"id": 142,
		"name": "任桂花",
		"phone": "18258124270",
		"createTime": "2020-05-14 13:40:12",
		"status": 1
	}, {
		"id": 145,
		"name": "蒋丽清",
		"phone": "15336557451",
		"createTime": "2020-06-09 08:58:30",
		"status": 1
	}, {
		"id": 148,
		"name": "石柳 ",
		"phone": "13187314692",
		"createTime": "2020-06-15 10:52:27",
		"status": 1
	}, {
		"id": 151,
		"name": "李庆",
		"phone": "18658111730",
		"createTime": "2020-06-15 10:53:26",
		"status": 1
	}, {
		"id": 154,
		"name": "刘燕",
		"phone": "18685169846",
		"createTime": "2020-06-17 13:31:16",
		"status": 1
	}, {
		"id": 157,
		"name": "沈丙童",
		"phone": "17682334855",
		"createTime": "2020-06-21 19:10:56",
		"status": 1
	}, {
		"id": 160,
		"name": "王兴惠",
		"phone": "18052862209",
		"createTime": "2020-06-24 13:31:18",
		"status": 1
	}, {
		"id": 163,
		"name": "叶丹",
		"phone": "18967172325",
		"createTime": "2020-07-01 11:21:52",
		"status": 1
	}, {
		"id": 166,
		"name": "吴亚辉",
		"phone": "13905616743",
		"createTime": "2020-07-02 10:25:06",
		"status": 1
	}, {
		"id": 167,
		"name": "宋静斌",
		"phone": "13362140179",
		"createTime": "2020-08-25 14:06:02",
		"status": 1
	}]
}
"""