# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        为商户钱包充钱
    输入参数：
        "phone": 运营后台登陆账号,
        "pass": 运营后台登陆密码
        "cityCode": 运营后台登陆选择城市

        "tradeAmount": 充值数额
        "userphone": 被充值的账号
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from yyht.用户中心.api.店铺列表_test import TestCase店铺查询 as 店铺查询
from yyht.用户中心.api.修改钱包_test import TestCase修改钱包 as 修改钱包


class TestCase商店账户充钱(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "tradeAmount": "1",
            "userphone": "18958169259",
        })

    teststeps = [

        Step(
            RunTestCase("店铺查询").call(店铺查询).export(*["userId"])
        ),
        Step(
            RunTestCase("修改钱包").call(修改钱包)
        ),

    ]


if __name__ == "__main__":
    TestCase商店账户充钱().test_start()
