# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        bd添加手抄单任务
    输入参数：
        "regionName": 战区名称
        "disable": 战区是否可用，0-可用，1-不可用
    输出参数：
        "bdId":bd的id
        "bdPhone":bd领导的手机号
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from yyht.拼拼.api.拜访任务列表_test import TestCase拜访任务列表 as 拜访任务列表
from yyht.拼拼.api.修改任务_test import TestCase修改任务 as 修改任务

class TestCasebd添加手抄单任务(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        })

    teststeps = [
        Step(
            RunTestCase("拜访任务列表").with_variables(
                **{

                }
            ).call(拜访任务列表)
        ),
        Step(
            RunTestCase("修改任务").with_variables(
                **{

                }
            ).call(修改任务)
        ),

    ]


if __name__ == "__main__":
    TestCasebd添加手抄单任务().test_start()
