# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        给用户钱包充值
    输入参数：
        "userId":用户id
        "tradeAmount":充值数额
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase修改钱包(HttpRunner):

    config = Config("修改钱包").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "userId": "",
            "tradeAmount": ""
        })

    teststeps = [
        Step(
            RunRequest("/dev2_t/mall/user/changeWallet")
            .post("/mall/user/changeWallet")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "89",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "remark": "",
                    "tradeAmount": "$tradeAmount",
                    "tradeCode": 11,
                    "tradeNo": "",
                    "userId": "$userId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase修改钱包().test_start()
