# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        通过手机号进行店铺查询
    输入参数：
        "userphone":店铺手机号
        "zoneCode": 区域编码
        "streetCode": 街道编码
        "traIdList": 商圈ID列表
        "countEnabled": 是否开启行数统计,默认:true
        "shopType": 店铺类型
        "shopTag": 店铺标签
        "deliveryFlag": 货到付款标示
        "shopStatus": 店铺状态标示
        "levelId": 店铺等级id
        "bdId": 市场负责人
        "queryType": 查询的方式，1-店铺名称，2-店铺id，3-手机号，4-联系电话
        "queryValue": 查询的值
    输出参数：
        "userId":用户id
        "traName": 商圈名字
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase店铺查询(HttpRunner):

    config = Config("店铺查询").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "userphone": "13819857341",
            "zoneCode": "",
            "streetCode": "",
            "traIdList": "-1",
            "countEnabled": "true",
            "shopType": "",
            "shopTag": "",
            "deliveryFlag": "",
            "shopStatus": "",
            "levelId": "",
            "bdId": "",
            "queryType": "3",
            "queryValue": "$userphone",

        }).export(*["userId", "traName"])

    teststeps = [
        Step(
            RunRequest("/dev2_t/mall/user/shopList")
            .get("/mall/user/shopList")
            .with_params(
                **{
                    "zoneCode": "$zoneCode",
                    "streetCode": "$streetCode",
                    "traIdList": "$traIdList",
                    "countEnabled": "$countEnabled",
                    "shopType": "$shopType",
                    "shopTag": "$shopTag",
                    "deliveryFlag": "$deliveryFlag",
                    "shopStatus": "$shopStatus",
                    "levelId": "$levelId",
                    "bdId": "$bdId",
                    "queryType": "$queryType",
                    "queryValue": "$queryValue",
                    "pageNum": "1",
                    "pageSize": "10",
                }
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            ).extract()
            .with_jmespath("body.body.pageData[0].userId","userId")
            .with_jmespath("body.body.pageData[0].traName","traName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase店铺查询().test_start()

"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1598344170,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 1,
		"totalSize": 1,
		"pageData": [{
			"registeredTime": 1596004207000,
			"userId": "51596004207293672",
			"shopId": 324696,
			"shopName": "万家超市",
			"shopType": "00",
			"shopTypeName": "便利店",
			"headerPics": "https://images.alpha.pinpianyi.cn/images/common/5d4316493ee549bb9fbc2e010d2f85e0.jpg",
			"geoCityName": null,
			"zoneCode": "330110",
			"zoneName": "余杭区",
			"streetCode": "330110102",
			"streetName": "塘栖镇",
			"shopAddress": "康盛小区120-1号",
			"contactUserName": "周先生",
			"registerMobile": "13588018966",
			"contactMobilePhone": "13588018969",
			"shopStatus": 1,
			"shopStatusName": "正常",
			"cashOnDelivery": 1,
			"bdId": 6667,
			"bdName": "李云鹏",
			"examineStatus": 2,
			"memberLevel": "VIP1",
			"levelAlias": "普通会员",
			"registerType": "BD邀请",
			"traName": "乔司临平-商圈",
			"orderTotalCount": 0,
			"orderTotalAmount": 0.00,
			"rechargeTotalAmount": 0.00,
			"walletAmount": 19.00
		}]
	}
}
"""