# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        用户密码登陆，获取登陆凭证
    输入参数：
        "phone": 供应商登陆用户名
        "pass": 登陆密码,
        "cityCode": 选择进入的城市号,
        "code": 钉钉获取的登陆验证码，默认1234
    输出参数：
        "session":登陆凭证
    前置接口：
        无
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from yyht.api.登陆用户验证_test import TestCase登陆用户验证 as 登陆用户验证
import env

class TestCase用户登陆(HttpRunner):

    config = Config("运营后台用户选择杭州登陆").verify(False).base_url("${testEnv($business,newweb)}").variables(
        **{
            "business": "yyht",
            "phone": env.phone,
            "pass": env.password,
            "cityCode": env.cityCode,
            "code": "1234",
        }).export(*["session"])

    teststeps = [
        Step(
            RunTestCase("登陆用户验证").call(登陆用户验证)
            .teardown_hook("${sleep_N_secs(1)}")
        ),
        Step(
            RunRequest("选择城市")
            .post("/ppy-auth/api/login/doLogin")
            .with_headers(
                **{
                    "systemCode": "yypp",
                }
            )
            .with_json(
                {
                    "mobile": "$phone",
                    "passwd": "$pass",
                    "code": "$code",
                    "cityCode": "$cityCode",
                }
            )
            .extract()
            .with_jmespath("body.body", "session")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase用户登陆().test_start()
