# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        展示账号信息
    输入参数：
        "id": bd id
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase展示账号信息(HttpRunner):

    config = Config("展示账号信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "id": "2"
        }).export(*["ldName"])

    teststeps = [
        Step(
            RunRequest("/test_t/pinpin/operator/getById")
            .get("/pinpin/operator/getById")
            .with_params(**{"id": "$id"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            ).extract()
            .with_jmespath("body.body.leaderName", "ldName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase展示账号信息().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1602763929,
	"signType": null,
	"sign": null,
	"body": {
		"id": 2,
		"user": "王子铭",
		"roleId": null,
		"phone": "13758178214",
		"department": "市场",
		"position": "BD",
		"jobNumber": 36,
		"sex": false,
		"createTime": "2017-07-26 15:29:52",
		"disabled": false,
		"inviteCode": "eeeeee",
		"cityCode": "330100",
		"leaderName": "邓虹雨",
		"leaderId": 619,
		"businessLine": 0
	}
}
"""