# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase操作司机出勤(HttpRunner):

    config = Config("操作司机出勤").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "wlApp",
            "phoneNumber": "15997336112",
            "token": "${getSession($business,$phoneNumber)}",
            "userId": "${getWlAppUserId($phoneNumber)}",
            "date": "${hapentime(0,3)}",
        }).export(*["body"])

    teststeps = [
        Step(
            RunRequest("/ppy-logis-driver-api/api/attendance/record")
            .post(
                "/ppy-logis-driver-api/api/attendance/record"
            )
            .with_headers(
                **{
                    "Content-Length": "152",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json(
                {
                    "body": {"date": "$date"},
                    "head": {
                        "channelId": "",
                        "platform": "Android",
                        "token": "$token",
                        "userId": "$userId",
                        "version": "2.13.1",
                    },
                }
            ).extract()
                .with_jmespath("body.body", "body")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase操作司机出勤().test_start()
