# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        司机确认取货数量
    输入参数：
       "amount": 商品数量,
        goodsId": 商品id,
        "classType":品类类型
        "orderIdList":订单列表,
        "pickupOrderId": 取货id,
    输出参数：
        "confirmVersion":司机点击确认的版本号
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase司机确认取货数量(HttpRunner):
    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "ebfc136d-fc32-45d6-bab1-99bdb2d3945e", "userId": "68",
            "amount": 10,
            "goodsId": 6565,
            "classType": 1,
            "orderIdList": "2020081112095511217762",
            "pickupOrderIdList": "1139206991308151070",
            "orderNo": ""
        }
    ).export(*["confirmVersion"])

    teststeps = [
        Step(
            RunRequest("司机确认取货数量")
                .post(
                "/ppy-logis-driver-api/pickup/confirmOrderByDriver"
            )
                .with_headers(
                **{
                    "Content-Length": "278",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.14.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
                .with_json(
                {
                    "body": {
                        "agentDriver": False,
                        "orderConfirmParamList": [
                            {
                                "classType": "$classType",  # 品类类型(1:A品类, 2：B品类)
                                "goodsList": [
                                    {
                                        "amount": "$amount",
                                        "goodsId": "$goodsId",
                                        "orderId": "$orderNo"
                                    }
                                ],
                                "orderIdList": ["$orderIdList"],
                                "pickupOrderId": "$pickupOrderIdList",
                            }
                        ],
                    },
                    "head": {
                        "channelId": "",
                        "platform": "Android",
                        "token": "$token",
                        "userId": "$userId",
                        "version": "${wlversion()}",
                    },
                }
            ).extract()
                .with_jmespath("body.body[0].confirmVersion", "confirmVersion")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase司机确认取货数量().test_start()

"""
request:
{
	"body": [{
		"agentDriver": false,
		"goodsList": [{
			"amount": 10,
			"goodsId": 10426
		}],
		"orderIdList": ["2020080519560212517621"],
		"pickupOrderId": "1135199801309941553"
	}],
	"head": {
		"channelId": "",
		"platform": "Android",
		"token": "14e6704b-154f-492d-a7ce-d7571211dac4",
		"userId": 68,
		"version": "2.11.2"
	}
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1596952509830",
	"timestamp": 1596952510,
	"signType": null,
	"sign": null,
	"body": [{
		"confirmVersion": 1600764,
		"pickupOrderId": 1135199801309941553
	}]
}
"""
