# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        司机app端提供二维码给供应商扫描确认取货
    输入参数：
        "confirmVersion": 取货单确认版本,
        "pickupOrderId": 取货id,
    输出参数：
        无
    前置接口：
        用户登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取供应商确认二维码信息(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "",
            "userId": "",
            "confirmVersion": 1111111,
            "pickupOrderIdList": 111111111111,
        }
    )

    teststeps = [

        Step(
            RunRequest("/ppy-logis-driver-api/pickup/queryConfirmURL")
            .post(
                "/ppy-logis-driver-api/pickup/queryConfirmURL"
            )
            .with_headers(
                **{
                    "Content-Length": "196",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.14.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json(
                {
                    "body": [
                        {
                            "confirmVersion": "$confirmVersion",
                            "pickupOrderId": "$pickupOrderIdList",
                        }
                    ],
                    "head": {
                        "channelId": "",
                        "platform": "Android",
                        "token": "$token",
                        "userId": "$userId",
                        "version": "${wlversion()}"},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取供应商确认二维码信息().test_start()

"""
request:
{
	"body": [{
		"confirmVersion": 1600719,
		"pickupOrderId": 1137694291308651203
	}],
	"head": {
		"channelId": "",
		"platform": "Android",
		"token": "14e6704b-154f-492d-a7ce-d7571211dac4",
		"userId": 68,
		"version": "2.11.2"
	}
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597025944009",
	"timestamp": 1597025944,
	"signType": null,
	"sign": null,
	"body": [{
		"pickupOrderId": 1137694291308651203,
		"supplierName": "拼便宜供应链",
		"confirmVersion": 1600719,
		"cloudStorageFlag": 0,
		"takePhotoSwitch": 1
	}]
}
"""