# NOTE: Generated By HttpRunner v3.1.3


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class   TestCase获取退货运单列表接口(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "",
            "userId": "",
            "supplierId": "10"
        }
    )

    teststeps = [
        Step(
            RunRequest("/ppy-logis-driver-api/returnWaybill/searchReturnWaybillPage")
            .post(
                "/ppy-logis-driver-api/returnWaybill/searchReturnWaybillPage"
            )
            .with_headers(
                **{
                    "Content-Length": "150",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.14.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json(
                {
                    "body": {"supplierId": "$supplierId"},
                    "head": {
                        "channelId": "",
                        "platform": "Android",
                        "token": "$token",
                        "userId": "$userId",
                        "version": "${wlversion()}"},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            ),
    ]


if __name__ == "__main__":
    TestCase获取退货运单列表接口().test_start()

"""
request:
{
	"body": {
		"supplierId": "9"
	},
	"head": {
		"channelId": "",
		"platform": "Android",
		"token": "a6495678-47fa-494c-a575-16e1ebcc7894",
		"userId": 256,
		"version": "2.11.2"
	}
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597127053482",
	"timestamp": 1597127053,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 0,
		"totalSize": 0,
		"pageData": []
	}
}
"""