# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        获取司机的基本信息
    输入参数：

    输出参数：

    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取司机的基本信息(HttpRunner):

    config = Config("获取司机的基本信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "",
            "userId": "",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-logis-driver-api/api/drivers/accountInfo")
            .post(
                "/ppy-logis-driver-api/api/drivers/accountInfo"
            )
            .with_headers(
                **{
                    "Content-Length": "134",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.14.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json(
                {
                    "body": {},
                    "head": {
                        "channelId": "",
                        "platform": "Android",
                        "token": "$token",
                        "userId": "$userId",
                        "version": "${wlversion()}"},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取司机的基本信息().test_start()
"""
request:
{
	"body": {},
	"head": {
		"channelId": "",
		"platform": "Android",
		"token": "ab286dbd-bf04-419b-a4fd-afc5f5bb8d16",
		"userId": 68,
		"version": "2.11.2"
	}
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597306170231",
	"timestamp": 1597306170,
	"signType": null,
	"sign": null,
	"body": {
		"avatarURL": null,
		"licensePlateNumber": "浙AK8M05",
		"driverName": "周兰涛",
		"driverPhoneNumber": "13738113393",
		"vehicleType": "金杯",
		"monthBillCount": 7,
		"servicePhone": "400-080-7070",
		"currentAmount": 1,
		"serviceManagerName": "高道林",
		"serviceManagerPhone": "15715763080",
		"upgradeDescription": null
	}
}
"""

