# NOTE: Generated By HttpRunner v3.1.3


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取未完成的运单列表(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "",
            "userId": "",
        }
    )

    teststeps = [
        Step(
            RunRequest("获取未完成的运单列表")
            .post(
                "/ppy-logis-driver-api/api/transportation/uncompletedOrders"
            )
            .with_headers(
                **{
                    "Content-Length": "135",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.14.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json(
                {
                    "body": {},
                    "head": {
                        "channelId": "",
                        "platform": "Android",
                        "token": "$token",
                        "userId": "$userId",
                        "version": "${wlversion()}"},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取未完成的运单列表().test_start()

"""
request:
{
	"body": {},
	"head": {
		"channelId": "",
		"platform": "Android",
		"token": "a6495678-47fa-494c-a575-16e1ebcc7894",
		"userId": 256,
		"version": "2.11.2"
	}
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597125923784",
	"timestamp": 1597125924,
	"signType": null,
	"sign": null,
	"body": {
		"unpaidOrderCount": null,
		"todayFinish": 0,
		"todayIncome": "0",
		"returnWarning": null,
		"transOrders": [{
			"transOrderId": 1139279801300871166,
			"no": 1,
			"goodsTypeAmount": 1,
			"goodsAmount": 10,
			"expectedIncome": "20.97",
			"plannedStartTime": 1597132800000,
			"receiverAmount": 1,
			"supplierAmount": 1,
			"thumbnailURL": null,
			"transOrderStatus": -100
		}]
	}
}
"""