# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase会员商品列表(HttpRunner):

    config = Config("会员商品列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        })

    teststeps = [
        Step(
            RunRequest("/test_t/mall/member/goods")
            .get("/mall/member/goods")
            .with_params(**{"pageNum": "1", "pageSize": "10"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase会员商品列表().test_start()

'''{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1600419617,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 84,
		"totalSize": 838,
		"pageData": [{
			"goodsId": 37,
			"goodsName": "已售罄-娃哈哈纯净水596ml*24瓶（每店限一件）-废弃",
			"memberGoodsId": 5192,
			"startTime": "2020-09-19 00:00:00",
			"endTime": "2020-10-31 00:00:00",
			"sellPrice": 23.00,
			"memberPrice": 20.00,
			"status": 0,
			"traId": 11,
			"traName": "滨江-商圈",
			"memberLevel": "VIP2-黄金会员",
			"recommend": 0,
			"createUser": 3328,
			"createUserName": "郑和",
			"createTime": "2020-09-18 17:00:16",
			"sellOut": 0
		}, {
			"goodsId": 53,
			"goodsName": "（新老包装随机）美汁源果粒橙420ml*12瓶",
			"memberGoodsId": 5191,
			"startTime": "2020-09-10 15:31:00",
			"endTime": "2020-09-18 00:00:00",
			"sellPrice": 32.00,
			"memberPrice": 30.00,
			"status": 2,
			"traId": 11,
			"traName": "滨江-商圈",
			"memberLevel": "VIP2-黄金会员",
			"recommend": 1,
			"createUser": 4712,
			"createUserName": "宋静斌",
			"createTime": "2020-09-10 15:30:52",
			"sellOut": 0
		}, {'''
