# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase创建组合套餐信息(HttpRunner):

    config = Config("创建组合套餐信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        })

    teststeps = [
        Step(
            RunRequest("/beta_t/mall/shopping/combo/meal/create")
            .post(
                "/mall/shopping/combo/meal/create"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "2429",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "launchSubject": 1,
                    "comboName": "鍥哄畾濂楅\ue635",
                    "useRedPacket": 0,
                    "comboDescription": "鍥哄畾濂楅\ue635",
                    "time": ["2020-09-17 00:00:00", "2020-10-31 23:59:59"],
                    "business": [11, 13, 14, 15, 20, 104, 171, 173, 174, 177, 178],
                    "initStock": 999,
                    "maxBuyCount": 5,
                    "comboType": 1,
                    "minMatchNumber": 1,
                    "comboGoodsList": [
                        {
                            "goodsNumber": 2,
                            "promotionsPrice": 25.24,
                            "comboChoice": 1,
                            "minPrice": 25.25,
                            "sortIndex": 0,
                            "goodsId": 390,
                            "goodsName": "鎬″疂绾\ue21a噣姘�1.55L*12鐡�",
                            "goodsSpecification": "1.55L*12鐡�/绠�",
                            "minSupplierGoodsQuote": 22.5,
                            "goodsPrices": [
                                {
                                    "traId": 171,
                                    "traName": "鏉\ue15e窞涓嬫矙涔濆牎-鎷兼槗璐�",
                                    "spellPrice": 25.25,
                                },
                                {
                                    "traId": 173,
                                    "traName": "鏉\ue15e窞钀у北-鎷兼槗璐�",
                                    "spellPrice": 25.25,
                                },
                                {
                                    "traId": 174,
                                    "traName": "鏉\ue15e窞婊ㄦ睙-鎷兼槗璐�",
                                    "spellPrice": 25.25,
                                },
                                {
                                    "traId": 177,
                                    "traName": "鏉\ue15e窞鍩庡寳-鎷兼槗璐�",
                                    "spellPrice": 25.25,
                                },
                                {
                                    "traId": 178,
                                    "traName": "鏉\ue15e窞涔斿徃涓村钩-鎷兼槗璐�",
                                    "spellPrice": 25.25,
                                },
                                {"traId": 11, "traName": "婊ㄦ睙-鍟嗗湀", "spellPrice": 25.5},
                                {
                                    "traId": 13,
                                    "traName": "鍩庡寳瑗挎箹-鍟嗗湀",
                                    "spellPrice": 25.5,
                                },
                                {
                                    "traId": 14,
                                    "traName": "涓嬫矙涔濆牎-鍟嗗湀",
                                    "spellPrice": 25.5,
                                },
                                {
                                    "traId": 15,
                                    "traName": "涔斿徃涓村钩-鍟嗗湀",
                                    "spellPrice": 25.5,
                                },
                                {
                                    "traId": 104,
                                    "traName": "钀у北-鍟嗗湀",
                                    "spellPrice": 25.5,
                                },
                                {
                                    "traId": 20,
                                    "traName": "鎷间究瀹�-渚垮埄搴�",
                                    "spellPrice": 26,
                                },
                            ],
                            "grossProfit": "10.86",
                        },
                        {
                            "goodsNumber": 3,
                            "promotionsPrice": 12.29,
                            "comboChoice": 1,
                            "minPrice": 12.3,
                            "sortIndex": 0,
                            "goodsId": 550,
                            "goodsName": "搴峰笀鍌呭寘瑁呴ギ鐢ㄦ按1.5L*8鐡�",
                            "goodsSpecification": "1.5L*8鐡�/绠�",
                            "minSupplierGoodsQuote": 8,
                            "goodsPrices": [
                                {
                                    "traId": 20,
                                    "traName": "鎷间究瀹�-渚垮埄搴�",
                                    "spellPrice": 12.3,
                                },
                                {
                                    "traId": 171,
                                    "traName": "鏉\ue15e窞涓嬫矙涔濆牎-鎷兼槗璐�",
                                    "spellPrice": 12.87,
                                },
                                {
                                    "traId": 173,
                                    "traName": "鏉\ue15e窞钀у北-鎷兼槗璐�",
                                    "spellPrice": 12.87,
                                },
                                {
                                    "traId": 174,
                                    "traName": "鏉\ue15e窞婊ㄦ睙-鎷兼槗璐�",
                                    "spellPrice": 12.87,
                                },
                                {
                                    "traId": 177,
                                    "traName": "鏉\ue15e窞鍩庡寳-鎷兼槗璐�",
                                    "spellPrice": 12.87,
                                },
                                {
                                    "traId": 178,
                                    "traName": "鏉\ue15e窞涔斿徃涓村钩-鎷兼槗璐�",
                                    "spellPrice": 12.87,
                                },
                                {"traId": 11, "traName": "婊ㄦ睙-鍟嗗湀", "spellPrice": 13},
                                {
                                    "traId": 13,
                                    "traName": "鍩庡寳瑗挎箹-鍟嗗湀",
                                    "spellPrice": 13,
                                },
                                {
                                    "traId": 14,
                                    "traName": "涓嬫矙涔濆牎-鍟嗗湀",
                                    "spellPrice": 13,
                                },
                                {
                                    "traId": 15,
                                    "traName": "涔斿徃涓村钩-鍟嗗湀",
                                    "spellPrice": 13,
                                },
                                {"traId": 104, "traName": "钀у北-鍟嗗湀", "spellPrice": 13},
                            ],
                            "grossProfit": "34.91",
                        },
                    ],
                    "imageUrls": [
                        "http://images.alpha.pinpianyi.cn/images/common/8b6eeb989e1a45a3bbd7aa1b6f236596.png"
                    ],
                    "traIds": [11, 13, 14, 15, 20, 104, 171, 173, 174, 177, 178],
                    "startTime": "2020-09-17 00:00:00",
                    "endTime": "2020-10-31 23:59:59",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 4020)
            .assert_equal("body.msg", "参数校验错误: [traSelectionList投放商圈不能为空] ")
        ),
    ]


if __name__ == "__main__":
    TestCase创建组合套餐信息().test_start()
# {
# 	"statusCode": 4020,
# 	"msg": "参数校验错误: [traSelectionList投放商圈不能为空] ",
# 	"traceMsg": "traceId: null",
# 	"timestamp": 1600242620,
# 	"signType": null,
# 	"sign": null,
# 	"body": null
# }