# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase创建专题信息无活动专题(HttpRunner):

    config = Config("创建专题信息无活动专题").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "startTime": "2020-09-09 20:57:44",
            "endTime": "2020-10-07 20:54:44",
            "traIds": [11, 13, 14, 20, 104, 171, 173, 174, 177, 178, 386, 395],
        }).export("topicId")

    teststeps = [
        Step(
            RunRequest("/alpha_t/mall/shopping/topics/create")
            .post("/mall/shopping/topics/create")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "412",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "topicType": None,
                    "startTime": "$startTime",
                    "endTime": "$endTime",
                    "traIds": "$traIds",
                    "topicId": None,
                    "picUrl": "http://images.alpha.pinpianyi.cn/images/common/43b1c2b34c9a47b0b8b16bedfed6e981.png",
                    "topicName": "test_专题",
                    "topicRule": {"gradientList": [], "ruleType": None},
                    "picDisplay": True,
                    "noticeTextDisplay": True,
                    "noticeText": "和我代付IQ未付啦啦啦啦",
                }
            ).extract()
            .with_jmespath("body.body.topicId","topicId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase创建专题信息无活动专题().test_start()
'''
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1599483337,
	"signType": null,
	"sign": null,
	"body": {
		"topicId": 12152,
		"topicName": "test_专题",
		"topicType": null,
		"topicTypeText": null,
		"traNames": "滨江-商圈,城北西湖-商圈,下沙九堡-商圈,拼便宜-便利店,萧山-商圈,杭州下沙九堡1111,杭州萧山-拼易购,杭州滨江-拼易购,杭州城北-拼易购,杭州乔司临平-拼易购,xmy测试,once-便利店1",
		"picUrl": "http://images.alpha.pinpianyi.cn/images/common/43b1c2b34c9a47b0b8b16bedfed6e981.png",
		"goodsNum": null,
		"picDisplay": true,
		"startTime": "2020-09-07 20:57:44",
		"endTime": "2020-10-07 20:54:44",
		"status": 0,
		"recommend": false,
		"modifyTime": "2020-09-07 20:55:37",
		"modifyUserName": "郑和",
		"remark": null
	}
'''