# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        "startTime": "2020-10-19 13:57:22",--开始时间
            "endTime": "2020-11-18 13:55:22",---结束时间
            "traIds": [11],--对应商圈
            "assignType": 1,---指定用户类型 0 指定用户 1指定商圈 2指定标签用户
            "couponName": "领劵活动名称",
            "display": 1,---是否入口展示（0不显示，1显示）
            "labelName": "",---指定标签时传入用户标签名称
            "redPacketId": 240568, --- 红包ID
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase创建编辑领劵活动(HttpRunner):

    config = Config("创建编辑领劵活动").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "startTime": "2020-10-19 14:55:22",
            "endTime": "2020-11-18 13:55:22",
            "traIds": [11],
            "assignType": 1,
            "couponName": "领劵活动",
            "display": 1,
            "redPacketId": 240568,
        })

    teststeps = [
        Step(
            RunRequest("/test_t/mall/shopping/coupon/create")
            .post("/mall/shopping/coupon/create")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "203",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "startTime": "$startTime",
                    "endTime": "$endTime",
                    "traIds": "$traIds",
                    "assignType": "$assignType",
                    "couponName": "$couponName",
                    "display": "$display",
                    "labelName": "",
                    "redPacketId": "$redPacketId",
                    "userIds": [],
                    "initCount": "100",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase创建编辑领劵活动().test_start()
