# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase推送消息列表(HttpRunner):

    config = Config("推送消息列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        }).export(*["name"])

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-message/pushContent/getContent")
            .post(
                "/ppy-message/pushContent/getContent"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "157",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "startTime": "2020-10-04 20:07:07",
                    "endTime": "2022-10-11 20:07:07",
                    "pushType": 1,
                    "pageNum": 1,
                    "pageSize": 10,
                    "name": "",
                    "userId": "",
                    "status": None,
                    "appCode": None,
                }
            ).extract()
            .with_jmespath("body.body.pageData[0].name", "name")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase推送消息列表().test_start()

# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: null",
# 	"timestamp": 1603074870,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"pageData": [{
# 			"id": 1409429,
# 			"name": "杭州站_我的亲娘类",
# 			"title": "我的亲娘类\uD83D\uDE0D\uD83D\uDE0DHAHAHAHHAHAHAHAHHHHHHHHHHHHHHHHHHHHHHHHH",
# 			"content": "我的亲娘类\uD83D\uDE0D\uD83D\uDE0D",
# 			"status": 1,
# 			"appName": "拼便宜",
# 			"targetValue": "指定用户",
# 			"createOperatorName": "胡超_13170035182",
# 			"updateOperatorName": "胡超_13170035182",
# 			"createTime": "2020-10-18 11:46:18",
# 			"submitTime": "2020-10-18 11:46:18",
# 			"pathType": null,
# 			"pathValue": null,
# 			"pathValueDesc": null,
# 			"pathParam": null,
# 			"pushNum": 4,
# 			"pushNo": "PUSH1197927771086751168",
# 			"pushOnlineUv": 0,
# 			"verifyUv": 0,
# 			"clickUv": 0,
# 			"cleanupUv": 0,
# 			"pushFlag": 1,
# 			"showFlag": 1,
# 			"msgPicUrl": "images/message/e1317be49a684d96a17b548956814177.jpg",
# 			"thumbnailPicUrl": null,
# 			"failureFlag": 1,
# 			"failureTime": null
# 		}