# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        "operateType": -1  停用，启用
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新人礼包列表(HttpRunner):

    config = Config("新人礼包列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        }).export(*["bagName", "bagId", "status"])

    teststeps = [
        Step(
            RunRequest("/test_t/mall/giftBag/list")
            .post("/mall/giftBag/list")
            .with_headers(
                **{
                    "sessionId": "$session",
                    "systemCode": "yypp",
                }
            ).with_json({"pageNum": 1, "pageSize": 100})
            .extract()
            .with_jmespath("body.body.pageData[-2].bagId", "bagId")
            .with_jmespath("body.body.pageData[-2].status", "status")
            .with_jmespath("body.body.pageData", "pageData")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase新人礼包列表().test_start()
# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: null",
# 	"timestamp": 1603803366,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"pageNum": 1,
# 		"pageSize": 100,
# 		"pageCount": 1,
# 		"totalSize": 22,
# 		"pageData": [{
# 			"bagId": 14,
# 			"bagName": "新人礼包",
# 			"awardAmount": 18.00,
# 			"expireDays": 3,
# 			"dayOffset": 60,
# 			"status": 1,
# 			"statusName": null,
# 			"redPacketCount": 4,
# 			"redPacketTotalAmount": 64.00,
# 			"releaseCount": 314,
# 			"receiveCount": 309,
# 			"useCount": 0
# 		},