# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新增会员红包(HttpRunner):

    config = Config("新增会员红包").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "availableStartTime": "${hapentime(1)}"+":00",
            "availableEndTime":  "${hapentime(100)}"+":00",
            "packetName": "会员红包5块5",
        })

    teststeps = [
        Step(
            RunRequest("/beta_t/mall/redPacket")
            .post("/mall/redPacket")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "295",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "packetName": "$packetName",
                    "instructions": "",
                    "receiveType": "09",
                    "packetType": "02",
                    "availableOrderAmount": 0,
                    "packetAmount": 5.5,
                    "timeType": 0,
                    "availableGoodsType": 1,
                    "goodsAttributes": [],
                    "availableStartTime": "$availableStartTime",
                    "availableEndTime": "$availableEndTime",
                    "userLimitCount": "5",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增会员红包().test_start()

'''{
    "statusCode":2000,
    "msg":null,
    "traceMsg":"traceId: null",
    "timestamp":1600159995,
    "signType":null,
    "sign":null,
    "body":true
}'''
