# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新增Tool(HttpRunner):

    config = Config("新增Tool").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "toolName": "test_工具",
        })

    teststeps = [
        Step(
            RunRequest("/alpha_t/mall/homeTool/add")
            .post("/mall/homeTool/add")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "240",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "actionContent": "3",
                    "actionType": "app",
                    "authorized": True,
                    "traIds": [],
                    "picUrl": "http://images.alpha.pinpianyi.cn/images/common/7eb5bf3e3a9c4eb3b7420622dd9b9e12.jpg",
                    "searchPicUrl": "",
                    "actionParam": "",
                    "toolName": "$toolName",
                    "toolId": None,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增Tool().test_start()
