# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新增广告(HttpRunner):

    config = Config("新增广告").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "launchName": "广告_郑小和",
            "startTime": "2020-12-1 16:00:00",
            "endTime": "2020-12-31 16:00:00",
        })

    teststeps = [
        Step(
            RunRequest("/mall/shopping/launch/create")
            .post("/mall/shopping/launch/create")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "719",
                    "Accept": "application/json, text/plain, */*",
                    "Sec-Fetch-Dest": "empty",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "actionContent": "1",
                    "traIds": [11],
                    "actionParam": "",
                    "actionType": "newMiNi",
                    "endTime": "$endTime",
                    "launchName": "$launchName",
                    "picUrl": "http://images.alpha.pinpianyi.cn/images/common/0300e0e2cf754e3590feb57ac05efd7a.jpg",
                    "startTime": "$startTime",
                    "traSelectionList": [
                        {"traId": 11, "checked": True},
                        {"traId": 13, "checked": False},
                        {"traId": 14, "checked": False},
                        {"traId": 15, "checked": False},
                        {"traId": 20, "checked": False},
                        {"traId": 104, "checked": False},
                        {"traId": 171, "checked": False},
                        {"traId": 173, "checked": False},
                        {"traId": 174, "checked": False},
                        {"traId": 177, "checked": False},
                        {"traId": 178, "checked": False},
                        {"traId": 353, "checked": False},
                        {"traId": 355, "checked": False},
                        {"traId": 357, "checked": False},
                        {"traId": 358, "checked": False},

                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增广告().test_start()
