# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新增浮窗(HttpRunner):

    config = Config("新增浮窗").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "floatingWindowName": "浮窗_郑小和",
        }).export(*["msg"])

    teststeps = [
        Step(
            RunRequest("/mall/floatingWindow")
            .post("/mall/floatingWindow")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "348",
                    "Accept": "application/json, text/plain, */*",
                    "Sec-Fetch-Dest": "empty",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "actionParam": "",
                    "actionType": "app",
                    "actionContent": "11",
                    "authorized": True,
                    "endTime": "2020-12-19 14:53:45",
                    "floatingWindowId": "",
                    "floatingWindowName": "$floatingWindowName",
                    "picUrl": "http://images.alpha.pinpianyi.cn/images/common/41b3ae2199704e8cbe4408bc730c00c5.jpg",
                    "startTime": "2020-09-21 14:53:45",
                    "traSelectionList": [{"traId": 11, "checked": True}],
                }
            ).extract()
            .with_jmespath("body.msg", "msg")
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal("body.statusCode", 2000)
            # .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增浮窗().test_start()
