# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新增专题(HttpRunner):

    config = Config("新增专题").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "startTime": "2020-10-01 00:00:00",
            "endTime": "2020-11-30 23:59:59",
            "topicName": "专题_郑小和",
        })

    teststeps = [
        Step(
            RunRequest("/test_t/mall/topic/add")
            .post("/mall/topic/add")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "314",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "actionContent": "4",
                    "actionType": "app",
                    "authorized": True,
                    "traIds": [11],
                    "picUrl": "http://images.alpha.pinpianyi.cn/images/common/a5ac5d07db1442c098bada247832ad72.png",
                    "searchPicUrl": "",
                    "actionParam": "",
                    "startTime": "$startTime",
                    "endTime": "$endTime",
                    "topicName": "$topicName",
                    "topicId": None,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增专题().test_start()
