# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase根据商品Id或名称模糊搜索商品(HttpRunner):

    config = Config("根据商品Id或名称模糊搜索商品").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "goodsId":"",
        }).export("goodsId")

    teststeps = [
        Step(
            RunRequest("/beta_t/mall/shopping/combo/meal/getGoodsInfo")
            .get(
                "/mall/shopping/combo/meal/getGoodsInfo"
            )
            .with_params(
                **{"traIds": "11,13,14,15,20,104,171,173,174,177,178", "goodsId": "$goodsId"}
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            ).extract()
            .with_jmespath("body.body[0].goodsId","goodsId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase根据商品Id或名称模糊搜索商品().test_start()
'''{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1600242439,
	"signType": null,
	"sign": null,
	"body": [{
		"goodsId": 174,
		"goodsName": "（大）百岁山天然矿泉水570ml*24瓶"
	}, {
		"goodsId": 390,
		"goodsName": "怡宝纯净水1.55L*12瓶"
	}, {
		"goodsId": 495,
		"goodsName": "怡宝纯净水4.5L*4瓶"
	}, {
		"goodsId": 550,
		"goodsName": "康师傅包装饮用水1.5L*8瓶"
	}, {
		"goodsId": 3323,
		"goodsName": "蒂花之秀沐浴露 法国香水 紫900ml*1瓶"
	}, {
		"goodsId": 4704,
		"goodsName": "优珍苏打水350ml*24瓶"
	}, {
		"goodsId": 4707,
		"goodsName": "上海盐汽水 600ml*24瓶"
	}, {
		"goodsId": 5175,
		"goodsName": "(3种口味随机)RIO锐澳水果鸡尾酒混合装 330ml*24罐"
	}, {
		"goodsId": 6561,
		"goodsName": "箭牌益达热带水果12片装 32g*10盒"
	}, {
		"goodsId": 8381,
		"goodsName": "水晶鸟8骨55cm经典英伦格子晴雨伞 1把"
	}, {
		"goodsId": 8459,
		"goodsName": "潘婷洗发露水润滋养 200ml*1瓶（9430）"
	}, {
		"goodsId": 8791,
		"goodsName": "沙宣洗发露水润去屑 200ml*1瓶(0061)"
	}, {
		"goodsId": 8799,
		"goodsName": "飘柔洗发露兰花长效洁顺（水润） 750ml*1瓶（9621）"
	}, {
		"goodsId": 10151,
		"goodsName": "得力 黑色 按动式中性笔 0.5mm签字笔水笔  S01"
	}, {
		"goodsId": 10155,
		"goodsName": "得力连中三元0.5mm黑色全针管学生中性水笔签字笔 S66"
	}, {
		"goodsId": 10166,
		"goodsName": "水晶鞋刷 去污洗鞋刷子 洗衣刷子 10支装 颜色随机 882"
	}, {
		"goodsId": 10477,
		"goodsName": "宜新 350ml保龄球麦香塑壳玻璃杯便携简约水杯 Z-129"
	}, {
		"goodsId": 10478,
		"goodsName": "宜新 400ml防滑塑壳玻璃杯便携简约水杯 Z-30"
	}, {
		"goodsId": 10479,
		"goodsName": "宜新 400ml镂空塑壳玻璃杯便携简约水杯 Z-29"
	}, {
		"goodsId": 10481,
		"goodsName": "宜新 450ml麦香塑壳玻璃杯便携水杯 Z-133"
	}, {
		"goodsId": 10482,
		"goodsName": "宜新 500ml塑玻杯水杯 玻璃杯 Z-113"
	}, {
		"goodsId": 11376,
		"goodsName": "白象接袖加棉防水手套乳胶手套 1双 BX-8055"
	}, {
		"goodsId": 11450,
		"goodsName": "佳洁士牙膏天然多效草本水晶清爽薄荷90g*6盒 5834"
	}, {
		"goodsId": 11571,
		"goodsName": "晨光高级碳素墨水AICW9001"
	}, {
		"goodsId": 11652,
		"goodsName": "宜新 麦香口杯洗漱口杯 水杯子 5208-1"
	}, {
		"goodsId": 11656,
		"goodsName": "11CM大号不锈钢口杯水杯子 ZJ11"
	}, {
		"goodsId": 11662,
		"goodsName": "康美 卡通塑料口杯水杯子 3040 3035"
	}, {
		"goodsId": 11663,
		"goodsName": "康美 塑料印花字口杯水杯子 5335"
	}, {
		"goodsId": 11664,
		"goodsName": "宜新 时尚简约水杯洗漱口杯子 颜色随机 2082"
	}, {
		"goodsId": 11665,
		"goodsName": "宜新 防滑水杯洗漱口杯子 颜色随机 8288"
	}, {
		"goodsId": 11666,
		"goodsName": "宜新 枫叶防滑带手柄水杯洗漱口杯子 颜色随机 8289"
	}, {
		"goodsId": 11668,
		"goodsName": "康美 双色卡通印花 塑料杯 漱口杯 水杯 3077 3243"
	}, {
		"goodsId": 11670,
		"goodsName": "康美 小熊印花双套杯 塑料杯 漱口杯 水杯 3293 3291"
	}, {
		"goodsId": 11671,
		"goodsName": "康美 方口卡通印花双套塑料口杯 漱口杯 水杯 3276"
	}, {
		"goodsId": 11678,
		"goodsName": "宜新 懒熊印花 塑料口杯子 漱口杯 水杯 3037"
	}, {
		"goodsId": 11679,
		"goodsName": "宜新 透明塑料口杯子 漱口杯 水杯 5859"
	}, {
		"goodsId": 11680,
		"goodsName": "宜新 菱形简约塑料口杯 漱口杯 水杯 2163"
	}, {
		"goodsId": 11681,
		"goodsName": "宜新 萌熊印花塑料口杯 漱口杯 水杯 5856"
	}, {
		"goodsId": 11682,
		"goodsName": "宜新 水果印花塑料口子 漱口杯 水杯 2156"
	}, {
		"goodsId": 11683,
		"goodsName": "康美小兔子口杯水杯子 3071"
	}, {
		"goodsId": 11684,
		"goodsName": "康美仙人掌口杯水杯子 3310"
	}, {
		"goodsId": 11686,
		"goodsName": "康美小熊口杯水杯子 3096 3220"
	}, {
		"goodsId": 11688,
		"goodsName": "康美ART皇冠双套杯口杯水杯子 3288"
	}, {
		"goodsId": 11689,
		"goodsName": "康美双套杯口杯水杯子 3316"
	}, {
		"goodsId": 11789,
		"goodsName": "宜新 3格筷子笼沥水盒挂式免打孔筷子筷笼 B-305"
	}, {
		"goodsId": 11790,
		"goodsName": "宜新 2格塑料筷笼沥水置物架  颜色随机 WS-B005"
	}, {
		"goodsId": 11851,
		"goodsName": "康美 大号透明水晶不带盖 佳品香皂盒 肥皂盒 5691"
	}, {
		"goodsId": 11860,
		"goodsName": "松紧花边玫瑰加厚橡胶乳胶洗碗手套防水塑胶胶皮家务耐用冬季加绒8888"
	}, {
		"goodsId": 11885,
		"goodsName": "得力迷你型胶水 可爱通用液体胶 35ml  7301"
	}, {
		"goodsId": 15120,
		"goodsName": "水立方男吹气鞋 柔软防滑塑胶凉拖鞋 XX-308 43码*1双"
	}, {
		"goodsId": 16879,
		"goodsName": "中香坊水果面包90g*1包"
	}, {
		"goodsId": 19315,
		"goodsName": "得力手工胶水 双头白乳胶 胶水35ml 6354"
	}, {
		"goodsId": 20299,
		"goodsName": "六神花露水大号195ml*1瓶"
	}, {
		"goodsId": 20503,
		"goodsName": "清亮7986多功能不锈钢水果刀颜色随机单把"
	}, {
		"goodsId": 20527,
		"goodsName": "浪莎 春秋超薄5D水晶袜（肤色）任意剪防勾丝水晶连裤袜美腿丝袜打底袜"
	}, {
		"goodsId": 20533,
		"goodsName": "浪莎 水晶丝女薄透短丝袜（每包5双装）一等品 肤色"
	}, {
		"goodsId": 20536,
		"goodsName": "浪莎 水晶丝女薄透短丝袜（每包5双装）一等品 黑色"
	}, {
		"goodsId": 20683,
		"goodsName": "金号  高档毛巾 纯棉吸水 加厚大122克 男女面巾 成人情侣洗脸巾"
	}, {
		"goodsId": 20719,
		"goodsName": "馨柏丽 纯棉LOVE桃心毛巾提花断档全棉吸水毛巾M1602"
	}, {
		"goodsId": 20722,
		"goodsName": "馨柏丽 超细纤维毛巾纳米吸水30*70洗车理发擦车巾干发巾"
	}, {
		"goodsId": 20746,
		"goodsName": "洁丽雅 经典毛巾全棉吸水毛巾 纯棉面巾洗脸巾 0450 一等品 单条包装 多色混发"
	}, {
		"goodsId": 20764,
		"goodsName": "洁丽雅 纯棉毛巾6633情侣毛巾柔软舒适强吸水 一等品 单条包装"
	}, {
		"goodsId": 20770,
		"goodsName": "洁丽雅 童巾纱布毛巾特柔强吸水宝宝儿童巾 可爱小兔8238"
	}, {
		"goodsId": 21019,
		"goodsName": "六神花露水195ML*1瓶 （7017）"
	}, {
		"goodsId": 21022,
		"goodsName": "六神花露水（普通款） 95ml*1瓶 （7024）"
	}, {
		"goodsId": 23527,
		"goodsName": "弘丰加厚塑料水瓢水勺子10*28颜色随机（TY-501）100g*1个"
	}, {
		"goodsId": 24265,
		"goodsName": "新宝遇水开花伞黑胶晴雨伞两用防晒伞太阳伞（女）防紫外线三折叠（遮阳伞）"
	}, {
		"goodsId": 24283,
		"goodsName": "天堂伞307E碰雨伞8股加固商务伞（高密拒水碰击布一甩干不沾水）藏青色"
	}, {
		"goodsId": 24286,
		"goodsName": "天堂伞正品3311E碰高密拒水碰击布三折晴雨伞10骨伞（藏青色）"
	}, {
		"goodsId": 24388,
		"goodsName": "六神快速止痒花露水180ml*1瓶 （4115）"
	}, {
		"goodsId": 24394,
		"goodsName": "六神花漾清新喷雾花露水180ml*1瓶 （7420）"
	}, {
		"goodsId": 29146,
		"goodsName": "清亮1575时尚浴帽沐浴洗澡防水浴帽单个装多色混发1只*1包"
	}, {
		"goodsId": 29320,
		"goodsName": "炫迈无糖口香糖水密西瓜味50.4g*9盒"
	}, {
		"goodsId": 31441,
		"goodsName": "宜新600ml便携时尚简约水杯 Z-155（1只*1包）"
	}, {
		"goodsId": 36826,
		"goodsName": "洁丽雅6415毛巾纯棉强吸水舒适柔软面巾劳保福利礼品巾一等品1条*1袋"
	}, {
		"goodsId": 37963,
		"goodsName": "弘丰37.5*13cm 水果彩色洗脸盆塑料盆(hx1003)1个*1个"
	}, {
		"goodsId": 37978,
		"goodsName": "弘丰37.5*14cm 半透明水果洗脸盆塑料盆(hx8162)1个*1个"
	}, {
		"goodsId": 37996,
		"goodsName": "弘丰30*26cm塑料水桶半透明双色(hx8830)1个*1个"
	}, {
		"goodsId": 38098,
		"goodsName": "HX38cm大号胶棉拖把不锈钢收缩挤水拖把（3821）1把*1把"
	}, {
		"goodsId": 38104,
		"goodsName": "HX28cm特惠款挤水速干防硬胶棉拖把（2700）1把*1把"
	}, {
		"goodsId": 38350,
		"goodsName": "水之帮手压泵水器1个*1盒 8074"
	}, {
		"goodsId": 40621,
		"goodsName": "万利达2.3L*1个电热水壶 yl-523"
	}, {
		"goodsId": 40639,
		"goodsName": "竹木年华祛痱止痒竹露水60g*1瓶 1584"
	}, {
		"goodsId": 68950,
		"goodsName": "农夫山泉饮用天然水塑封550ml*24瓶"
	}]
}'''