# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase红包列表(HttpRunner):

    config = Config("红包列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        }).export("packetId", "pageData")

    teststeps = [
        Step(
            RunRequest("/mall/redPacket")
            .get("/mall/redPacket")
            .with_params(
                **{
                    "packetName": "",
                    "receiveType": "",
                    "status": "",
                    "pageNum": "1",
                    "pageSize": "10",
                }
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Sec-Fetch-Dest": "empty",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            ).extract()
            .with_jmespath("body.body.pageData[0].packetId", "packetId")
            .with_jmespath("body.body.pageData", "pageData")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase红包列表().test_start()
'''{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1600161422,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 960,
		"totalSize": 9595,
		"pageData": [{
			"packetId": 233773,
			"packetName": "会员",
			"cityCode": "330100",
			"preferentialText": "无门槛，减5.50",
			"userTimeText": "2020-09-22 00:00:00-2020-09-30 00:00:00",
			"maxReleaseCount": 0,
			"receivedCount": 0,
			"receiveType": "09",
			"receiveTypeName": "会员红包",
			"availableGoodsText": "所有商品",
			"createUser": "郑和",
			"createTime": "2020-09-15 17:17:01",
			"status": 0,
			"statusDesc": "待审核"
		}, {
			"packetId": 233772,
			"packetName": "会员",
			"cityCode": "330100",
			"preferentialText": "无门槛，减5.50",
			"userTimeText": "2020-09-22 00:00:00-2020-09-30 00:00:00",
			"maxReleaseCount": 0,
			"receivedCount": 0,
			"receiveType": "09",
			"receiveTypeName": "会员红包",
			"availableGoodsText": "所有商品",
			"createUser": "郑和",
			"createTime": "2020-09-15 17:14:45",
			"status": 0,
			"statusDesc": "待审核"
		}, {'''

