# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取红包审核信息详情(HttpRunner):

    config = Config("获取红包审核信息详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "packetId": "",
        }).export(*["packetName"])

    teststeps = [
        Step(
            RunRequest("/mall/redPacket/$packetId/examine")
            .get("/mall/redPacket/$packetId/examine")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Sec-Fetch-Dest": "empty",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            ).extract()
            .with_jmespath("body.body.packetName", "packetName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取红包审核信息详情().test_start()
'''{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1600162077,
	"signType": null,
	"sign": null,
	"body": {
		"packetId": 233773,
		"packetName": "会员",
		"instructions": "",
		"receiveType": "09",
		"receiveTypeText": "会员红包",
		"orderAmountText": "无门槛，减5.50",
		"userTimeText": "2020-09-22 00:00:00-2020-09-30 00:00:00",
		"availableGoodsText": "所有商品",
		"availableUserType": null,
		"labelName": "",
		"grantReason": null,
		"grantUserCount": null,
		"grantTimeText": null,
		"createUser": "郑和",
		"createTime": "2020-09-15 17:17:01"
	}
}'''
