# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取当前城市商圈列表(HttpRunner):

    config = Config("获取当前城市商圈列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        })

    teststeps = [
        Step(
            RunRequest("/mall/tra/topics/selections")
            .get("/mall/tra/topics/selections")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Sec-Fetch-Dest": "empty",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取当前城市商圈列表().test_start()
'''{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1600225346,
	"signType": null,
	"sign": null,
	"body": [{
		"traId": 11,
		"traName": "滨江-商圈",
		"checked": false
	}, {
		"traId": 13,
		"traName": "城北西湖-商圈",
		"checked": false
	}, {
		"traId": 14,
		"traName": "下沙九堡-商圈",
		"checked": false
	}, {
		"traId": 15,
		"traName": "乔司临平-商圈",
		"checked": false
	}, {
		"traId": 20,
		"traName": "拼便宜-便利店",
		"checked": false
	}, {
		"traId": 104,
		"traName": "萧山-商圈",
		"checked": false
	}, {
		"traId": 171,
		"traName": "杭州下沙九堡-拼易购",
		"checked": false
	}, {
		"traId": 173,
		"traName": "杭州萧山-拼易购",
		"checked": false
	}, {
		"traId": 174,
		"traName": "杭州滨江-拼易购",
		"checked": false
	}, {
		"traId": 177,
		"traName": "杭州城北-拼易购",
		"checked": false
	}, {
		"traId": 178,
		"traName": "杭州乔司临平-拼易购",
		"checked": false
	}, {
		"traId": 353,
		"traName": "临安卫星城-便利店",
		"checked": false
	}, {
		"traId": 355,
		"traName": "湖州卫星城吴兴便利店",
		"checked": false
	}, {
		"traId": 357,
		"traName": "富阳卫星城-便利店",
		"checked": false
	}, {
		"traId": 358,
		"traName": "卫星城湖州-德清商圈",
		"checked": false
	}]
}'''