# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        "status": "",返利商品状态_status:1:已过期、2:生效、3:未生效不传表示全部
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase返利商品列表(HttpRunner):

    config = Config("返利商品列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "status": "",
        }).export(*["pageData"])

    teststeps = [
        Step(
            RunRequest("/test_t/mall/rebate/list")
            .post("/mall/rebate/list")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "71",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "pageNum": 1,
                    "pageSize": 10,
                    "goodsName": "",
                    "status": "$status",
                    "rebateMoney": "",
                }
            ).extract()
            .with_jmespath("body.body.pageData", "pageData")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase返利商品列表().test_start()
# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: null",
# 	"timestamp": 1603954054,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"pageNum": 1,
# 		"pageSize": 10,
# 		"pageCount": 6,
# 		"totalSize": 57,
# 		"pageData": [{
# 			"rebateId": 244,
# 			"cityCode": "330100",
# 			"goodsId": 473,
# 			"goodsName": "喜力啤酒大瓶装500ml*12瓶/箱",
# 			"rebateAmount": 1.00,
# 			"startTime": "2020-10-18 10:40:55",
# 			"endTime": "2020-11-17 10:40:39",
# 			"disabled": 0,
# 			"deleted": 0,
# 			"createTime": "2020-10-18 10:40:42",
# 			"modifyTime": "2020-10-18 10:40:42",
# 			"orderCount": 0,
# 			"cityName": "杭州站",
# 			"statusName": "生效中/启用中",
# 			"validStatus": "生效中",
# 			"disabledStatus": "启用中"
# 		}