# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase领劵活动列表(HttpRunner):

    config = Config("领劵活动列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
        }).export(*["couponName"])

    teststeps = [
        Step(
            RunRequest("/test_t/mall/shopping/coupon/list")
            .post("/mall/shopping/coupon/list")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "119",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "statusArray": [],
                    "traId": "",
                    "queryName": "",
                    "pageNum": 1,
                    "pageSize": 10,
                    "redPacketName": "",
                    "couponId": "",
                    "couponName": "",
                }
            ).extract()
            .with_jmespath("body.body.pageData[0].couponName", "couponName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase领劵活动列表().test_start()
# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: null",
# 	"timestamp": 1603093826,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"pageNum": 1,
# 		"pageSize": 10,
# 		"pageCount": 5,
# 		"totalSize": 45,
# 		"pageData": [{
# 			"couponId": 349,
# 			"couponName": "领劵活动7",
# 			"redPacketId": 240587,
# 			"redPacketInfo": "无门槛，减1.10",
# 			"display": 1,
# 			"pushCount": 570,
# 			"receiveCount": 0,
# 			"useCount": 0,
# 			"traNames": "滨江-商圈",
# 			"startTime": "2020-10-19 15:25:22",
# 			"endTime": "2020-11-18 13:55:22",
# 			"status": 1,
# 			"updateUserName": "胡超",
# 			"updateTime": "2020-10-19 15:24:28",
# 			"remark": null,
# 			"initCount": 100,
# 			"receivedCount": 0
# 		}