# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        上传用户头像
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from files.fileData import *

class TestCase上传用户头像(HttpRunner):

    config = Config("上传用户头像").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "account": "",
            "token": "${getSession($business,$account)}",
        }).export(*["headerPics"])

    teststeps = [
        Step(
            RunRequest("/ppy-mall/user/photo")
            .post("/user/photo")
            .with_headers(
                **{
                    "Accept": "application/json",
                    "Version": "4.6.0",
                    "channel": "app",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Content-Type": "application/json",
                    "sessionId": "$token",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "User-Agent": "FightCheap/4.6.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "Content-Length": "21859",
                    "serviceName": "MALL",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {
                    "fileBase64Data": 有效营业执照
                }
            ).extract()
            .with_jmespath("body.body", "headerPics")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase上传用户头像().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603094340,
	"signType": null,
	"sign": null,
	"body": "https://images.pinpianyi.com/images/common/58c7a16a658a4552a92982b3e8c6af3f.jpg"
}
"""