# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        创建订单
    输入参数：

    输出参数：
        "orderNo": 订单编号,
    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase创建订单(HttpRunner):

    config = Config("创建订单").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "phone": "18958169259",
            "token": "${getSession($business,$phone)}",
            "cashOnDelivery": False,
            "deliverRuleCode": "1"
        }).export(*["orderNo"])

    teststeps = [
        Step(
            RunRequest("/ppy-mall/orders")
            .post("/orders")
            .with_headers(
                **{
                    "serviceName": "MALL",
                    "channel": "app",
                    "deviceId": "2cdf701146c959d296b4b455f9623536",
                    "version": "4.4.0",
                    "sessionId": "$token",
                    "Content-Length": "46",
                    "Connection": "close",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.0",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json({"cashOnDelivery": "$cashOnDelivery", "deliverRuleCode": "$deliverRuleCode"})
            .extract()
            .with_jmespath("body.body.orderNo","orderNo")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase创建订单().test_start()

"""
request:
{
	"cashOnDelivery": false,
	"deliverRuleCode": "1"
}
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1597216902,
	"signType": null,
	"sign": null,
	"body": {
		"orderNo": "2020081216003211214686",
		"orderAmount": 87120,
		"balanceAmount": 2763900,
		"freightAmount": 0,
		"redPacketDeductedAmount": 0,
		"alipay": 10,
		"wechat": 20,
		"bailingPay": null,
		"bailingPayAvailableAmount": null,
		"bailingPayText": null,
		"swiftpassAlipayScan": null,
		"swiftpassWechatScan": null,
		"paymentAmount": 87120
	}
}"""