# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        发起支付
    输入参数：
        "orderNo":订单编号
    输出参数：

    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase发起支付(HttpRunner):

    config = Config("发起支付").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "token": "${getSession($business,$phone)}",
            "tradeChannel": 10,
            "useBalance": True,
            "orderNo": ""
        })

    teststeps = [
        Step(
            RunRequest("/ppy-mall/orders/2020081216003211214686/payment")
            .post(
                "/orders/$orderNo/payment"
            )
            .with_headers(
                **{
                    "serviceName": "MALL",
                    "channel": "app",
                    "deviceId": "2cdf701146c959d296b4b455f9623536",
                    "version": "4.4.0",
                    "sessionId": "$token",
                    "Content-Length": "37",
                    "Connection": "close",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.0",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json({"tradeChannel": "$tradeChannel", "useBalance": "$useBalance"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase发起支付().test_start()
