# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        商品详情页相似推荐查询
    输入参数：
        "goodsId": 商品id
    输出参数：

    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase商品详情页相似推荐查询(HttpRunner):

    config = Config("商品详情页相似推荐查询").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "",

            "goodsId": "98158",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-mall/search/goods/similar/39085")
            .get(
                "/search/goods/similar/$goodsId"
            )
            .with_headers(
                **{
                    "serviceName": "MALL",
                    "channel": "app",
                    "deviceId": "2cdf701146c959d296b4b455f9623536",
                    "version": "4.4.0",
                    "sessionId": "$token",
                    "Connection": "close",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.0",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase商品详情页相似推荐查询().test_start()
