# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        账号注册
    输入参数：
        "account": 注册号码
    输出参数：
        "token": 登陆凭证
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase帐号注册(HttpRunner):

    config = Config("帐号注册").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "token": "",
            "account": "13366666666",
        }).export(*["token"])

    teststeps = [
        Step(
            RunRequest("/ppy-mall/user/account/register")
            .post("/user/account/register")
            .with_headers(
                **{
                    "Accept": "application/json",
                    "Version": "4.6.0",
                    "channel": "app",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Content-Type": "application/json",
                    "sessionId": "$token",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "User-Agent": "FightCheap/4.6.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "Content-Length": "51",
                    "serviceName": "MALL",
                    "Connection": "keep-alive",
                }
            )
            .with_json({"account": "$account", "verificationCode": "0000"})
            .extract()
            .with_jmespath("body.body.token","token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase帐号注册().test_start()
"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603089066,
	"signType": null,
	"sign": null,
	"body": {
		"token": "77dDI3qpTH1hJqXaAMuc2tS1HxhAnGNPCZ1p0Ym3PkLp6eQEig9m6gZV7/oeMRHJdoH06NqlCpdkHw0kDSsTE4lhNcAHsUMy44kRne3JwTJ9XgAPNIp/HAO2OpT7pGNGGFZG1y1xMD3WfOVmDEKmAA==",
		"message": "注册成功",
		"registerCode": null,
		"giftBagVO": null
	}
}
"""