# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        购物车添加商品
    输入参数：
        "goodsNu": 商品数量,
        "goodsId": 商品id,
    输出参数：

    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase添加商品(HttpRunner):

    config = Config("添加商品").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "account": "17629262213",
            "token": "${getSession($business,$account)}",

            "goodsNu": 15,
            "goodsId": "39085",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-mall/user/cart")
            .post("/user/cart")
            .with_headers(
                **{
                    "serviceName": "MALL",
                    "channel": "app",
                    "deviceId": "2cdf701146c959d296b4b455f9623536",
                    "version": "4.4.0",
                    "sessionId": "$token",
                    "Content-Length": "140",
                    "Connection": "close",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.0",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .with_json(
                {
                    "cartAdd": False,
                    "channel": "商品详情页",
                    "eventId": "1597215305734-15001-goods:$goodsId",
                    "goodsCount": "$goodsNu",
                    "goodsId": "$goodsId",
                    "preGoods": False,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase添加商品().test_start()
