# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        获取app广告页列表
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取App广告页列表(HttpRunner):

    config = Config("获取App广告页列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "account": "",
            "token": "${getSession($business,$account)}",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-mall/app/launch")
            .get("/app/launch")
            .with_headers(
                **{
                    "channel": "app",
                    "Version": "4.6.0",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept": "application/json",
                    "sessionId": "$token",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "User-Agent": "FightCheap/4.6.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "serviceName": "MALL",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取App广告页列表().test_start()
