# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        查看登陆用户信息
    输入参数：
        无
    输出参数：
        无
    前置接口：
        验证码登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取当前用户资料(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "phone": "18958169259",
            "token": "${getSession($business,$phone)}",
        })
    teststeps = [
        Step(
            RunRequest("/ppy-mall/user")
            .get("/user")
            .with_headers(
                **{
                    "serviceName": "MALL",
                    "channel": "app",
                    "deviceId": "2cdf701146c959d296b4b455f9623536",
                    "sessionId": "$token",
                    "Connection": "close",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.0",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取当前用户资料().test_start()

"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1597136570,
	"signType": null,
	"sign": null,
	"body": {
		"shopId": "317051",
		"account": "13606714877",
		"shopName": "馨妈零食屋",
		"contactUserName": "任又香",
		"contactMobilePhone": "13606714877",
		"headerPics": "https://images.pinpianyi.com/images/common/545418fcaf884280a7772d29afe26e03.jpg",
		"cityCode": "330100",
		"cityName": "杭州市",
		"zoneCode": "330109",
		"zoneName": "萧山区",
		"streetCode": "330109008",
		"streetName": "河庄街道",
		"shopType": "00",
		"shopTypeText": "便利店",
		"shopAddress": "河中路120号",
		"longitude": 120.464093,
		"latitude": 30.287734,
		"statusCode": 2000,
		"message": "用户信息正常",
		"errorUrl": null,
		"iconUrl": "https://images.pinpianyi.com/images/face/LOGISTICS_795f389138384d28923bd765f6bd2a70.jpg",
		"labelColor": "#919191",
		"memberLevel": "普通会员",
		"landmarkName": "中发人才公寓",
		"landmarkAddress": "河庄大江东河庄街道河中路120号中发人才公寓",
		"businessLicense": null
	}
}
"""