# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        获取订单详情
    输入参数：
        "orderNo":订单编号
    输出参数：

    前置接口：
        验证码登陆
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase获取订单详情(HttpRunner):

    config = Config("获取订单详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "token": "",
            "orderNo": "2020082617115816219527",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-mall/orders/2020081216003211214686")
            .get(
                "/orders/$orderNo"
            )
            .with_headers(
                **{
                    "serviceName": "MALL",
                    "channel": "app",
                    "deviceId": "2cdf701146c959d296b4b455f9623536",
                    "version": "4.4.0",
                    "sessionId": "$token",
                    "Connection": "close",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.0",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取订单详情().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1597217564,
	"signType": null,
	"sign": null,
	"body": {
		"orderNo": "2020081216003211214686",
		"orderStatus": "240",
		"orderStatusText": "待发货",
		"payStatus": null,
		"payStatusText": null,
		"expireTime": null,
		"cashOnDelivery": false,
		"predictDeliverDate": null,
		"skuCount": null,
		"goodsCount": null,
		"amountOrder": null,
		"amountFreight": 0,
		"amountPayment": 87120,
		"amountRedPacketDeducted": 0,
		"amountWalletPayment": 87120,
		"amountActualPayment": 87120,
		"amountLack": null,
		"amountReturn": null,
		"amountRefund": null,
		"timeCreate": 1597216902000,
		"timePayment": 1597217560000,
		"timeRefund": null,
		"timeComplete": null,
		"goodsList": null,
		"packageList": [{
			"deliveryOrderNo": 0,
			"viewDeliveryNo": null,
			"deliveryOrderStatus": "3",
			"deliveryOrderStatusDesc": "待发货",
			"planTime": 1597303960000,
			"skuCount": 1,
			"goodsCount": 15,
			"goodsList": [{
				"promotionsType": "00",
				"promotionsTypeText": null,
				"mainImageUrl": "https://images.pinpianyi.com/images/common/images/face/GOODS_39085_33768797.jpg",
				"goodsName": "合慧原味烤肠70g*35根/袋",
				"specification": "70g*35根/袋",
				"goodsPacketUnit": "袋",
				"originalOrderNo": null,
				"orderNo": "2020081216003211214686",
				"goodsId": 39085,
				"sellsPrice": 5808,
				"promotionsPrice": null,
				"countTotal": 15,
				"countSells": null,
				"countPromotions": null,
				"countReceived": null,
				"countLack": null,
				"countReturn": null,
				"amountTotal": 87120,
				"amountReturn": null,
				"amountLack": null,
				"amountRedPacket": 0,
				"preferentialAmount": 0,
				"amountPayment": 87120,
				"amountRebate": 0,
				"amountRebateText": "返0.00元/件",
				"hotDiscount": null,
				"refundCount": null,
				"refundReason": null,
				"actualRefundAmount": null,
				"sellLabel": "供应商自配",
				"serviceLabelList": []
			}],
			"payOnDelivery": null
		}],
		"containRefund": false,
		"cancelFlag": true,
		"cancelReasonList": [{
			"reasonCode": 0,
			"reasonDesc": "商品数量或种类需调整"
		}, {
			"reasonCode": 1,
			"reasonDesc": "收货信息有误"
		}, {
			"reasonCode": 2,
			"reasonDesc": "有更优惠的购买方案"
		}, {
			"reasonCode": 3,
			"reasonDesc": "重复下单"
		}, {
			"reasonCode": 4,
			"reasonDesc": "支付遇到问题"
		}, {
			"reasonCode": 5,
			"reasonDesc": "暂时无法收货"
		}, {
			"reasonCode": 6,
			"reasonDesc": "一直未发货"
		}, {
			"reasonCode": 7,
			"reasonDesc": "我不想买了"
		}, {
			"reasonCode": 8,
			"reasonDesc": "其他原因"
		}],
		"logisticsFlag": false,
		"amountGoods": 87120,
		"amountMoneyOff": 0,
		"payChannel": "余额支付",
		"cancelTag": "温馨提示：</br>1、限时抢购、活动资格等优惠可能会一并取消</br>2、订单一经取消，无法恢复",
		"promAmount": 0,
		"memberAmount": 0,
		"totalPreferentialAmount": 0,
		"aftersaleButton": false
	}
}
"""