# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        重置密码
    输入参数：
        "account": 用户账号
        "shareCode": 邀请的bd id
        "newPassword": 新密码
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase重置密码(HttpRunner):

    config = Config("重置密码").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppyApp",
            "account": "13366666666",
            "shareCode": "706",
            "newPassword": "SS123456",
            "token": "${getSession($business,$account)}",
        }).export(*["token"])

    teststeps = [
        Step(
            RunRequest("/ppy-mall/user/account/resetPassword")
            .post("/user/account/resetPassword")
            .with_headers(
                **{
                    "Accept": "application/json",
                    "Version": "4.6.0",
                    "channel": "app",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Content-Type": "application/json",
                    "sessionId": "$token",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "User-Agent": "FightCheap/4.6.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "Content-Length": "68",
                    "serviceName": "MALL",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {
                    "account": "$account",
                    "shareCode": "$shareCode",
                    "newPassword": "$newPassword",
                }
            ).extract()
            .with_jmespath("body.body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.msg", "成功")
        ),
    ]


if __name__ == "__main__":
    TestCase重置密码().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": "成功",
	"traceMsg": "traceId: null",
	"timestamp": 1603106157,
	"signType": null,
	"sign": null,
	"body": {
		"token": "77dDI3qpTH1hJqXaAMuc2hKjHy8gxoDi0J4d3SZOIH4fm13r/5tqo+MAxM+xysWQKSxAjA6sydQ5mNLWaM1rzcM1iVxTNZ0Mb94LXl5rRerS7zRhyE+4FYyJnbNuo2J9CV0MR++za4FDxuSbevIiWQ=="
	}
}
"""