#! /usr/bin/env python
#-*- coding:utf-8 -*-

#author:bingo

# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        使指定运单生效
    输入参数：
        "phone": 运营后台登陆账号
        "pass": 运营后台登陆密码
        "cityCode": 城市编号
        "orderNo": 订单号
    输出参数：
        无
    前置接口：
        验证码登陆
"""

from httprunner import HttpRunner, Config, Step, RunTestCase
from yyht.物流中心.运单管理.api.运单列表_test import TestCase运单列表 as 运单列表
from yyht.物流中心.运单管理.api.运单详情_test import TestCase运单详情 as 运单详情
from yyht.物流中心.运单管理.api.运单生效_test import TestCase运单生效 as 运单生效


class TestCase运单生效(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "pd",
            "session": "${getSession($business)}",
            "orderNo": "2020081417331211611694",
        })
    teststeps = [
        Step(
            RunTestCase("查看运单列表").call(运单列表).export(*["transOrderId"])
        ),
        Step(
            RunTestCase("查看运单详情").call(运单详情)
        ),
        Step(
            RunTestCase("运单生效").call(运单生效)
        ),
    ]


if __name__ == "__main__":
    TestCase运单生效().test_start()
