# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        bd战区预校验
    输入参数：
        "bdId": bd id
        "regionId": 战区id
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseBd战区预校验(HttpRunner):

    config = Config("Bd战区预校验").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "bdId": "1",
            "regionId": "498"
        })

    teststeps = [
        Step(
            RunRequest("/test_t/pinpin/regionBdRel/preCheck")
            .get("/pinpin/regionBdRel/preCheck")
            .with_params(**{"bdId": "$bdId", "regionId": "$regionId"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseBd战区预校验().test_start()
