# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        新增战区
    输入参数：
        "cityCode": 城市站编码
        "geoCityCode": 城市编码
        "colour": 战区背景
        "createTime": 创建时间
        "disable": 是否可用，0-不可用，1-可用
        "regionArea": 战区面积
        "regionId": 战区id
        "regionName": 战区名称
        "regionPointsList": 战区经纬度点位
        "updateTime": 更新时间
        "principalId": 负责人id
        "businessLine": 业务线, 0-城市站, 1-卫星城
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env


class TestCase新增战区(HttpRunner):

    config = Config("新增战区").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "cityCode": env.cityCode,
            "geoCityCode": env.cityCode,
            "colour": "#3a91ec",
            "createTime": "",
            "disable": False,
            "regionArea": 7865306,
            "regionId": "",
            "regionName": "aaaa",
            "regionPointsList": [
                [119.363917, 30.15791],
                [119.400782, 30.143883],
                [119.357995, 30.120351],
            ],
            "updateTime": "",
            "principalId": 4,
            "businessLine": 0,
        })

    teststeps = [
        Step(
            RunRequest("/test_t/pinpin/region/insert")
            .post("/pinpin/region/insert")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "288",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "cityCode": "$cityCode",
                    "geoCityCode": "$geoCityCode",
                    "colour": "$colour",
                    "createTime": "$createTime",
                    "disable": "$disable",
                    "regionArea": "$regionArea",
                    "regionId": "$regionId",
                    "regionName": "$regionName",
                    "regionPointsList": "$regionPointsList",
                    "updateTime": "$updateTime",
                    "principalId": "$principalId",
                    "businessLine": "$businessLine",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase新增战区().test_start()

"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1602815470,
	"signType": null,
	"sign": null,
	"body": {
		"regionId": 498,
		"regionName": "aaaa",
		"regionArea": "7865306",
		"regionPointsList": [
			[119.363917, 30.15791],
			[119.400782, 30.143883],
			[119.357995, 30.120351]
		],
		"colour": "#3a91ec",
		"cityCode": "330100",
		"geoCityCode": "330100",
		"disable": false,
		"createTime": "2020-10-16 10:31:10",
		"updateTime": "2020-10-16 10:31:10",
		"principalId": 4,
		"businessLine": 0
	}
}
"""