# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        添加战区bd关系，将bd绑定到战区
    输入参数：
        "bdId": bd id
        "regionId": 战区id
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase添加战区Bd关系(HttpRunner):

    config = Config("添加战区Bd关系").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "bdId": "1",
            "regionId": "498"
        })

    teststeps = [
        Step(
            RunRequest("/test_t/pinpin/regionBdRel/addRegionBdRel")
            .post(
                "/pinpin/regionBdRel/addRegionBdRel"
            )
            .with_params(**{"bdId": "$bdId", "regionId": "$regionId"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "2",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase添加战区Bd关系().test_start()
