# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        BD售后管理列表
    输入参数：
        "queryType": 列表类型，0，待确认/1，售后中,/2，已完成
        "queryValue": 查询值
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseBd售后管理列表(HttpRunner):

    config = Config("Bd售后管理列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "13797912089",
            "session": "${getSession($business,$phone)}",
            "queryType": "0",
            "queryValue": ""
        })

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/afterSale/afterSaleRecord")
            .get("/afterSale/afterSaleRecord")
            .with_params(
                **{"pageNum": "1", "pageSize": "10", "queryType": "$queryType", "queryValue": "$queryValue"}
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "channel": "app",
                    "appname": "",
                    "Accept-Language": "zh-cn",
                    "Accept-Encoding": "gzip, deflate",
                    "platform": "ios",
                    "Content-Type": "application/json",
                    "sessionid": "$session",
                    "deviceid": "1F8ED797-D036-4BA3-BEAA-A176B0E08BD6",
                    "User-Agent": "Pinpin/3.7.0.2 CFNetwork/889.9 Darwin/17.2.0",
                    "appchannel": "appstore",
                    "servicename": "NEW-PP",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCaseBd售后管理列表().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603073546,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": null,
		"pageSize": null,
		"pageCount": null,
		"totalSize": null,
		"pageData": null
	}
}
"""