# NOTE: Generated By HttpRunner v3.1.4
# FROM: pinpin\api\发送验证码.har


"""
    概要：
        账号获取验证码
    输入参数：
        "ppsession": "",
        "phone": "15869038912"
    输出参数：
        无
    前置接口：
        无
"""



from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase发送验证码(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "phone": "15869038912"
        }
    )

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/user/account/sendSmsCode")
            .post(
                "/user/account/sendSmsCode"
            )
            .with_headers(
                **{
                    "sessionId": "$session",
                    "serviceName": "NEW-PP",
                    "Content-Length": "24",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                    "deviceId": "3834e10b-cb2a-34c6-85f2-2ae3b365eb14",
                }
            )
            .with_json({"mobile": "$phone"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", "success")
        ),
    ]


if __name__ == "__main__":
    TestCase发送验证码().test_start()
