# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        市场人员列表
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase市场人员列表(HttpRunner):

    config = Config("市场人员列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "13861683296",
            "session": "${getSession($business,$phone)}",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/user/account/marketBdList")
            .post("/user/account/marketBdList")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "channel": "app",
                    "appname": "",
                    "Accept-Language": "zh-cn",
                    "Accept-Encoding": "gzip, deflate",
                    "platform": "ios",
                    "Content-Type": "application/json",
                    "sessionid": "$session",
                    "deviceid": "1F8ED797-D036-4BA3-BEAA-A176B0E08BD6",
                    "Content-Length": "0",
                    "appchannel": "appstore",
                    "servicename": "NEW-PP",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase市场人员列表().test_start()
"""
response:
body     : {
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: null",
    "timestamp": 1603955065,
    "signType": null,
    "sign": null,
    "body": [
        {
            "operatorId": 9,
            "operatorName": "测试-杨涛",
            "phone": "18268186428",
            "department": "市场",
            "position": "DM"
        },
        {
            "operatorId": 161,
            "operatorName": "陈庆玉",
            "phone": "15869038912",
            "department": "市场",
            "position": "BD"
        },
        {
            "operatorId": 647,
            "operatorName": "黄燕辉",
            "phone": "13105538550",
            "department": "市场",
            "position": "BD"
        },
        {
            "operatorId": 1489,
            "operatorName": "宁建",
            "phone": "15757113586",
            "department": "市场",
            "position": "BD"
        },
        {
            "operatorId": 2674,
            "operatorName": "吕小强",
            "phone": "15168335473",
            "department": "市场",
            "position": "BD"
        },
        {
            "operatorId": 7843,
            "operatorName": "陈华琼",
            "phone": "18605888539",
            "department": "市场",
            "position": "BD"
        }
    ]
}
"""