# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        店铺属性配置列表
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase店铺属性配置列表(HttpRunner):

    config = Config("店铺属性配置列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "18758166686",
            "session": "${getSession($business,$phone)}",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/myCustomer/getShopStatusCfg")
            .get("/myCustomer/getShopStatusCfg")
            .with_headers(
                **{
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "serviceName": "NEW-PP",
                    "Accept": "*/*",
                    "Version": "3.7.0",
                    "User-Agent": "Pinpin/3.7.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase店铺属性配置列表().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603424963,
	"signType": null,
	"sign": null,
	"body": [{
		"shopStatus": 1,
		"shopStatusDesc": "高频用户"
	}, {
		"shopStatus": 2,
		"shopStatusDesc": "中频用户"
	}, {
		"shopStatus": 3,
		"shopStatusDesc": "低频用户"
	}, {
		"shopStatus": 4,
		"shopStatusDesc": "存活用户"
	}, {
		"shopStatus": 5,
		"shopStatusDesc": "休眠用户"
	}, {
		"shopStatus": 6,
		"shopStatusDesc": "注册未激活"
	}]
}
"""