# NOTE: Generated By HttpRunner v3.1.4
"""
   概要：
        拜访店铺用户分层详情
    输入参数：
        "queryBdId": 要查寻详情的BdId
        "queryBd": true-查询bd排行 false-查询团队排行
        "dateType": 时间类型 今日 1,昨日 2, 本周 3, 本月 4, 上月 5
    输出参数：

    前置接口：
        用户登录
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase拜访店铺用户分层详情(HttpRunner):

    config = Config("拜访店铺用户分层详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "18556816816",
            "session": "${getSession($business,$phone)}",
            "queryBdId": "161",
            "queryBd": "true",
            "dateType": "4",
        })

    teststeps = [
        Step(
            RunRequest("拜访管理数据监控接口")
            .get(
                "/vDashboard/visitDetail"
            )
            .with_params(**{"queryBdId": "$queryBdId", "queryBd": "$queryBd", "dateType": "$dateType"})
            .with_headers(
                **{
                    "sessionId": "$session",
                    "serviceName": "NEW-PP",
                    "Content-Length": "115",
                    "Connection": "Keep-Alive",
                    "Accept-Encoding": "gzip",
                    "User-Agent": "okhttp/3.12.1",
                    "Content-Type": "application/json",
                    "Accept-Language": "zh-CN,zh;q=0.8",
                    "deviceId": "3834e10b-cb2a-34c6-85f2-2ae3b365eb14",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase拜访店铺用户分层详情().test_start()
"""
response:
body     : {
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: null",
    "timestamp": 1603956994,
    "signType": null,
    "sign": null,
    "body": [
        {
            "oLastMonthMemberLevel": "V1",
            "vUserCount": 1,
            "vCoverage": 0.3333,
            "vCoverageText": "33.33%",
            "vAverageTime": 2,
            "vAverageTimeText": "2''",
            "bdId": 161,
            "bdName": "陈庆玉",
            "visitStartTime": "2020-10-28",
            "visitEndTime": "2020-10-28"
        },
        {
            "oLastMonthMemberLevel": "V2",
            "vUserCount": 2,
            "vCoverage": 0.6667,
            "vCoverageText": "66.67%",
            "vAverageTime": 1,
            "vAverageTimeText": "1''",
            "bdId": 161,
            "bdName": "陈庆玉",
            "visitStartTime": "2020-10-28",
            "visitEndTime": "2020-10-28"
        }
    ]
}
"""
