# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        拜访管理拜访分层接口
    输入参数：
        "dateType": 时间类型 今日 1,昨日 2, 本周 3, 本月 4, 上月 5
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase拜访管理拜访分层接口(HttpRunner):

    config = Config("拜访管理拜访分层接口").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "18556816816",
            "session": "${getSession($business,$phone)}",
            "dateType": "5"
        })

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/vDashboard/visitSlice")
            .get("/vDashboard/visitSlice")
            .with_params(**{"dateType": "$dateType"})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "channel": "app",
                    "appname": "",
                    "Accept-Language": "zh-cn",
                    "Accept-Encoding": "gzip, deflate",
                    "platform": "ios",
                    "Content-Type": "application/json",
                    "sessionid": "$session",
                    "deviceid": "1F8ED797-D036-4BA3-BEAA-A176B0E08BD6",
                    "appchannel": "appstore",
                    "servicename": "NEW-PP",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase拜访管理拜访分层接口().test_start()
"""
response:
body     : {
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: null",
    "timestamp": 1603954635,
    "signType": null,
    "sign": null,
    "body": [
        {
            "oLastMonthMemberLevel": "V0",
            "vUserCount": 2,
            "vCoverage": 0.2857,
            "vCoverageText": "28.57%",
            "vAverageTime": 142,
            "vAverageTimeText": "2'22''",
            "bdId": null,
            "bdName": null,
            "visitStartTime": null,
            "visitEndTime": null
        },
        {
            "oLastMonthMemberLevel": "V1",
            "vUserCount": 2,
            "vCoverage": 0.2857,
            "vCoverageText": "28.57%",
            "vAverageTime": 2,
            "vAverageTimeText": "2''",
            "bdId": null,
            "bdName": null,
            "visitStartTime": null,
            "visitEndTime": null
        },
        {
            "oLastMonthMemberLevel": "V2",
            "vUserCount": 2,
            "vCoverage": 0.2857,
            "vCoverageText": "28.57%",
            "vAverageTime": 1,
            "vAverageTimeText": "1''",
            "bdId": null,
            "bdName": null,
            "visitStartTime": null,
            "visitEndTime": null
        },
        {
            "oLastMonthMemberLevel": "V3",
            "vUserCount": 1,
            "vCoverage": 0.1429,
            "vCoverageText": "14.29%",
            "vAverageTime": 1,
            "vAverageTimeText": "1''",
            "bdId": null,
            "bdName": null,
            "visitStartTime": null,
            "visitEndTime": null
        }
    ]
}
"""