# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        查询bd未审核店铺数
    输入参数：
        无
    输出参数：
        "count":未审核数
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查询Bd未审核店铺数(HttpRunner):

    config = Config("查询Bd未审核店铺数").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "13797912089",
            "session": "${getSession($business,$phone)}",
        }).export(*["count"])

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/myCustomer/waitingCheckCount")
            .get("/myCustomer/waitingCheckCount")
            .with_headers(
                **{
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "serviceName": "NEW-PP",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "User-Agent": "Pinpin/3.7.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
            ).extract()
            .with_jmespath("body.body","count")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase查询Bd未审核店铺数().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603010582,
	"signType": null,
	"sign": null,
	"body": 1
}
"""