# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        查询基础数据
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查询基础数据(HttpRunner):

    config = Config("查询基础数据").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "session": "",
        })

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/stats/common")
            .get("/stats/common")
            .with_headers(
                **{
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "serviceName": "NEW-PP",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "User-Agent": "Pinpin/3.7.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase查询基础数据().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603007959,
	"signType": null,
	"sign": null,
	"body": {
		"rank": 2,   今日下单用户排名
		"unSign": 34,       今日未签到用户
		"shops": 251,       我的客户数
		"sevenDays": 251,    近7天未下单用户
		"thirtyDays": 196,      近30天未下单用户
		"orderShops": 0
	}
}
"""