# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        根据类型查询码表中的可用类型，店铺审核选择店铺类型
    输入参数：
        "dictCode": 类型代码,shopType类型，userCoverCrowd周边消费人群
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase根据类型查询码表中的可用类型(HttpRunner):

    config = Config("根据类型查询码表中的可用类型").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "13797912089",
            "session": "${getSession($business,$phone)}",
            "dictCode": "shopType"
        })

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/support/dictCode")
            .get("/support/dictCode")
            .with_params(**{"dictCode": "$dictCode"})
            .with_headers(
                **{
                    "channel": "app",
                    "Version": "3.7.0",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept": "application/json",
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "User-Agent": "Pinpin/3.7.0 (iPhone; iOS 11.1.2; Scale/3.00)",
                    "serviceName": "NEW-PP",
                    "Connection": "keep-alive",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase根据类型查询码表中的可用类型().test_start()
