# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        检查打卡条件是否满足
    输入参数：
        "signType": 打卡类型 signIn 签到 signOut 签退
        "currentLatitude": 当前定位维度,
        "currentLongitude": 当前定位经度,
        "shopLatitude": 店铺维度
        "shopLongitude": 店铺经度
        "shopId": 拜访店铺id
        "signId": 打卡记录id,当签退需要传值
        "shopType": 拜访对象类型不能为空 1 合作店铺 2 潜在店铺
    输出参数：
        "check_value":接口返回状态
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase检查打卡条件是否满足(HttpRunner):

    config = Config("检查打卡条件是否满足").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "15757113586",
            "session": "${getSession($business,$phone)}",
            "signType": "signIn",
            "currentLatitude": 0,
            "currentLongitude": 0,
            "shopLatitude": "30.263564",
            "shopLongitude": "120.183406",
            "shopId": 2331,
            "signId": None,
            "shopType": 1,
        }).export(*["check_value"])

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/visitRecord/checkSign")
            .post("/visitRecord/checkSign")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "channel": "app",
                    "appname": "",
                    "Accept-Language": "zh-cn",
                    "Accept-Encoding": "gzip, deflate",
                    "platform": "ios",
                    "Content-Type": "application/json",
                    "sessionid": "$session",
                    "deviceid": "1F8ED797-D036-4BA3-BEAA-A176B0E08BD6",
                    "Content-Length": "146",
                    "User-Agent": "Pinpin/3.7.1.20201023100053 CFNetwork/889.9 Darwin/17.2.0",
                    "appchannel": "appstore",
                    "servicename": "NEW-PP",
                    "Connection": "keep-alive",
                }
            )
            .with_json(
                {
                    "signType": "$signType",
                    "currentLatitude": "$currentLatitude",
                    "currentLongitude": "$currentLongitude",
                    "shopLatitude": "$shopLatitude",
                    "shopLongitude": "$shopLongitude",
                    "shopId": "$shopId",
                    "signId": "$signId",
                    "shopType": "$shopType",
                }
            )
            .extract()
            .with_jmespath("body.statusCode", "check_value")
            # debugtalk中用到此接口，返回值到debugtalk中判定
            # .validate()
            # .assert_equal("status_code", 200)
            # .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase检查打卡条件是否满足().test_start()
"""
response:
{
	"statusCode": 6000,
	"msg": "48小时内不能重复拜访同一店铺",
	"traceMsg": "underlying service internal biz exception, traceId: null, exception occurred at application: ppy-pinpin-app-core, serviceName: checkSignIn",
	"timestamp": 1604307054,
	"signType": null,
	"sign": null,
	"body": null
}
"""