# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        模糊查询无未审核店铺
    输入参数：
        "name": 店铺名称/手机号码
    输出参数：
        "WaitingCheckShopId":未审核店铺id
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase模糊查询无未审核店铺(HttpRunner):

    config = Config("模糊查询无未审核店铺").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "13797912089",
            "session": "${getSession($business,$phone)}",
            "name": "曙光"
        }).export(*["WaitingCheckShopId"])

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/myCustomer/selectWaitingCheck")
            .get("/myCustomer/selectWaitingCheck")
            .with_params(**{"name": "$name"})
            .with_headers(
                **{
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "serviceName": "NEW-PP",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
            ).extract()
            .with_jmespath("body.body[0].id","WaitingCheckShopId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase模糊查询无未审核店铺().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603074853,
	"signType": null,
	"sign": null,
	"body": [{
		"id": 320480,
		"shopName": "曙光",
		"rollPhone": "13277912957",
		"specificAddress": "逢火生鲜市场",
		"pics": "https://images.alpha.pinpianyi.cn/images/common/7d5aa52caa9c4f638f3206bd50fdb23e.jpg",
		"longitude": "114.299941999999990000",
		"latitude": "30.504541999999994000",
		"user": "黄威威"
	}]
}
"""