# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        照片上传
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from files.fileData import *


class TestCase照片上传(HttpRunner):

    config = Config("照片上传").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "15757113586",
            "session": "${getSession($business,$phone)}",
        }).export(*["picUrls"])

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/sign/uploadPic")
            .post("/sign/uploadPic")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Content-Type": "multipart/form-data; boundary=Boundary+21C49C7401B083B8",
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "Content-Length": "1005923",
                    "serviceName": "NEW-PP",
                    "Connection": "keep-alive",
                }
            )
            .with_data(
                {
                    "file": 有效营业执照
                }
            ).extract()
            .with_jmespath("body.body", "picUrls")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase照片上传().test_start()
