# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        获取个人信息
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

class TestCase获取个人信息(HttpRunner):

    config = Config("获取个人信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "ppApp",
            "phone": "13797912089",
            "session": "${getSession($business,$phone)}",
        }).export(*["bdId", "bdName", "regionName"])

    teststeps = [
        Step(
            RunRequest("/ppy-pinpin/user/account/info")
            .get("/user/account/info")
            .with_headers(
                **{
                    "sessionId": "$session",
                    "deviceId": "0380efdbdb0938af0d7a3852519f361a86ff",
                    "serviceName": "NEW-PP",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Accept-Language": "zh-Hans-CN;q=1",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
            ).extract()
            .with_jmespath("body.body.id","bdId")
            .with_jmespath("body.body.user","bdName")
            .with_jmespath("body.body.regionName", "regionName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase获取个人信息().test_start()
"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: null",
	"timestamp": 1603074045,
	"signType": null,
	"sign": null,
	"body": {
		"id": 706,
		"user": "王迪",
		"roleId": 123,
		"phone": "13797912089",
		"department": "市场",
		"position": "BDM",
		"jobnumber": 670,
		"sex": true,
		"createTime": 1553347120000,
		"inviteCode": "DB",
		"disabled": false,
		"cityCode": "420100",
		"leaderName": "詹元辉",
		"leaderId": 7417,
		"userId": 31553347119522333,
		"regionName": "武昌战队",
		"businessLine": 0,
		"isSatelliteBD": false
	}
}
"""