# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase司机钱包流水列表(HttpRunner):

    config = Config("司机钱包流水列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "driverId": "68",
            "tradeCode": []
        }).export(*["driverIds", "tradeNo"])

    teststeps = [
        Step(
            RunRequest("/ppy-finance-settle-api/logistics/wallet/log")
            .post(
                "https://webapi.test.pinpianyi.cn/ppy-finance-settle-api/logistics/wallet/log"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "58",
                    "Accept": "application/json, text/plain, */*",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {"pageNum": 1, "pageSize": 10, "driverId": "$driverId", "tradeCode": "$tradeCode"}
            ).extract()
                .with_jmespath("body.body.pageData[0].driverId","driverIds")
                .with_jmespath("body.body.pageData[0].tradeNo", "tradeNo")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase司机钱包流水列表().test_start()
"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1603179803929",
	"timestamp": 1603179803,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 4,
		"totalSize": 40,
		"pageData": [{
			"id": "1015934690551400089",
			"driverId": "68",
			"tradeNo": "13756",
			"tradeCode": "02",
			"tradeCodeValue": "钱包提现",
			"currentAmount": 372835,
			"guaranteeAmount": 100000,
			"tradeAmount": -372800,
			"createTime": "2020-06-30 06:17:35"
		}, {
			"id": "1015934572041400078",
			"driverId": "68",
			"tradeNo": "1015925068042200099",
			"tradeCode": "01",
			"tradeCodeValue": "结算转入",
			"currentAmount": 50,
			"guaranteeAmount": 100000,
			"tradeAmount": 372785,
			"createTime": "2020-06-30 03:00:04"
		}, {
			"id": "1015921725110600102",
			"driverId": "68",
			"tradeNo": "11764",
			"tradeCode": "02",
			"tradeCodeValue": "钱包提现",
			"currentAmount": 413950,
			"guaranteeAmount": 100000,
			"tradeAmount": -413900,
			"createTime": "2020-06-15 06:08:31"
		}, {
			"id": "1015921612020600124",
			"driverId": "68",
			"tradeNo": "1015912108082200256",
			"tradeCode": "01",
			"tradeCodeValue": "结算转入",
			"currentAmount": 0,
			"guaranteeAmount": 100000,
			"tradeAmount": 413950,
			"createTime": "2020-06-15 03:00:02"
		}, {
			"id": "1015907928863200235",
			"driverId": "68",
			"tradeNo": "9898",
			"tradeCode": "02",
			"tradeCodeValue": "钱包提现",
			"currentAmount": 276171,
			"guaranteeAmount": 100000,
			"tradeAmount": -276171,
			"createTime": "2020-05-30 06:54:46"
		}, {
			"id": "1015907788143200060",
			"driverId": "68",
			"tradeNo": "1015901740002200339",
			"tradeCode": "01",
			"tradeCodeValue": "结算转入",
			"currentAmount": 258171,
			"guaranteeAmount": 100000,
			"tradeAmount": 18000,
			"createTime": "2020-05-30 03:00:14"
		}, {
			"id": "1015907788033200082",
			"driverId": "68",
			"tradeNo": "1015898284060600272",
			"tradeCode": "01",
			"tradeCodeValue": "结算转入",
			"currentAmount": 0,
			"guaranteeAmount": 100000,
			"tradeAmount": 258171,
			"createTime": "2020-05-30 03:00:03"
		}, {
			"id": "1015890902803200200",
			"driverId": "68",
			"tradeNo": "8692",
			"tradeCode": "02",
			"tradeCodeValue": "钱包提现",
			"currentAmount": 330951,
			"guaranteeAmount": 100000,
			"tradeAmount": -330951,
			"createTime": "2020-05-10 13:58:00"
		}, {
			"id": "1015890508013200144",
			"driverId": "68",
			"tradeNo": "1015885324050600019",
			"tradeCode": "01",
			"tradeCodeValue": "结算转入",
			"currentAmount": 0,
			"guaranteeAmount": 100000,
			"tradeAmount": 330951,
			"createTime": "2020-05-10 03:00:01"
		}, {
			"id": "1015882102592400073",
			"driverId": "68",
			"tradeNo": "8263",
			"tradeCode": "02",
			"tradeCodeValue": "钱包提现",
			"currentAmount": 367398,
			"guaranteeAmount": 100000,
			"tradeAmount": -367398,
			"createTime": "2020-04-30 09:30:59"
		}]
	}
}
"""