# -*- coding: utf-8 -*-
#author:lixiaoguo
#company:pinpianyi
#createdate:2020/9/17 16:28

# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        输入供应商资料新增供应商
    输入参数：
        {
            "supplier": "新增供应商测试",                              供应商名称
            "supplierType": "1",                                       类型，1个体，2企业
            "companyName": "新增供应商测试",                           企业名称
            "street": "金一路",                                        供应商详细地址
            "graphicalPosition": "120.306704,30.205616",               供应商经纬度
            "amountPeriod": "1",                                       结算账期
            "user": "测试",                                            联系人
            "phone": 17629262213,                                      联系手机号
            "serviceManagerName": "",                                  服务主管
            "maxReserveVolume": 99999,                                 最大备货量
            "minQuantity": 0,                                          派单区间最小值
            "maxQuantity": 9999,                                       派单区间最大值
            "needConfirm": "1",                                        是否需要确认库存，1是
            "maxWorkGoodsNum": 9999,                                   最大作业件数
            "maxWorkVehicleNum": 9999,                                 最大作业车次
            "distribution": "1",                                       配送方式，1供应商自配
            "contractTime": "2020-09-17 16:25:49",                     签约时间
            "contractStartTime": "2020-09-01 16:00:00",                合同起止
            "contractEndTime": "2020-11-07 16:00:00",                  合同起止
            "coordinateLevel": 1,                                      供应商等级，1等级二
            "paymentType": "1",                                        收款信息
            "userName": "接口测试",                                    收款信息;开户名
            "accoutNo": "20201212",                                    收款信息;卡号
            "bankProvince": "浙江省",                                  收款信息;开户行
            "bankCity": "杭州市",                                      收款信息;开户行
            "bankName": "招商银行",                                    收款信息;开户行
            "bank": "拼便宜",                                          收款信息;详细地址
            "accountName": "接口测试",                                 账号信息：接口测试
            "rollPhone": 17629262213,                                  账号信息：手机号
            "id": "",
            "category": "3",                                           AB品类，3AB品类
            "supplierCategory": 10,                                     暂不清楚
            "registeredFund": 100,                                     注册资金(元)
            "businessLicense": "yyzz",                                 营业执照
            "idCard": "625987856113225555",                            身份证号
            "primaryAccount": 1,
            "storageArea": 40,                                         仓库面积
            "workerNumber": 4,                                         工人数
            "cars": 4,                                                 车辆
            "purchaseSaleStock": 1,                                    进销存系统
            "cashEatGoods": true,                                      是否愿意现金吃货，true愿意
            "supportCompanyProject": true,                             是否愿意无条件支持公司项目，true愿意
            "futurePayment": 4,                                        未来帐期提升至
            "picUrlList": ["http://images.alpha.pinpianyi.cn/images/supplier/contact_d629ebf1dd6544f2956367e56606badc.jpg"],    图片地址，附件
            "changRollP": "0",
            "supplierQualifications": [{                               供应商资质
                "qualificationId": 1,                                   营业执照
                "supplierId": ""
            }],
            "city": "杭州市",                                          供应商地址：市
            "geoCityCode": "330100",                                   供应商地址：市，code
            "zone": "萧山区",                                          供应商地址：区
            "zoneCode": "330109",                                      供应商地址：区code
            "traIdList": [13, 11],                                     供应商地址：覆盖商圈
            "pwd": "262213"                                            密码
        }
    输出参数：
        "supplierId":供应商id
        "storageId":仓库id
        "virtualStorageId":虚拟仓库id
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest


class TestCase新增供应商(HttpRunner):

    config = Config("新建供应商").verify(False).base_url("${testEnv(yyht_$env)}").variables(
        **{
            "env":"test",
            "session": "4c299fd3a54f4d989acaaa4babab6eb1",
            "phone": 17629262213,
            "rollPhone":17629262213,
            "businessLicense":'pinpianyi'

        })

    teststeps = [
        Step(
            RunRequest("/alpha_t/ppy-supplier-mng-api/supplier/addSupplier")
            .post(
                "/ppy-supplier-mng-api/supplier/addSupplier"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "74",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "supplier": "新增供应商测试",
                    "supplierType": "1",
                    "companyName": "新增供应商测试",
                    "street": "金一路",
                    "graphicalPosition": "120.306704,30.205616",
                    "amountPeriod": "1",
                    "user": "测试",
                    "phone": "$phone",
                    "serviceManagerName": "",
                    "maxReserveVolume": 99999,
                    "minQuantity": 0,
                    "maxQuantity": 9999,
                    "needConfirm": "1",
                    "maxWorkGoodsNum": 9999,
                    "maxWorkVehicleNum": 9999,
                    "distribution": "1",
                    "contractTime": "2020-09-17 16:25:49",
                    "contractStartTime": "2020-09-01 16:00:00",
                    "contractEndTime": "2020-11-07 16:00:00",
                    "coordinateLevel": 1,
                    "paymentType": "1",
                    "userName": "接口测试",
                    "accoutNo": "20201212",
                    "bankProvince": "浙江省",
                    "bankCity": "杭州市",
                    "bankName": "招商银行",
                    "bank": "拼便宜",
                    "accountName": "接口测试",
                    "rollPhone": "$rollPhone",
                    "id": "",
                    "category": "3",
                    "supplierCategory": 10,
                    "registeredFund": 100,
                    "businessLicense": "$businessLicense",
                    "idCard": "625987856113225555",
                    "primaryAccount": 1,
                    "storageArea": 40,
                    "workerNumber": 4,
                    "cars": 4,
                    "purchaseSaleStock": 1,
                    "cashEatGoods": True,
                    "supportCompanyProject": True,
                    "futurePayment": 4,
                    "picUrlList": [
                        "http://images.alpha.pinpianyi.cn/images/supplier/contact_d629ebf1dd6544f2956367e56606badc.jpg"],
                    "changRollP": "0",
                    "supplierQualifications": [{
                        "qualificationId": 1,
                        "supplierId": ""
                    }],
                    "city": "杭州市",
                    "geoCityCode": "330100",
                    "zone": "萧山区",
                    "zoneCode": "330109",
                    "traIdList": [13, 11],
                    "pwd": "123456"
                }
            ).extract()
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase新增供应商().test_start()
