# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        ruleId 毛利锁规则ID
        status  启用状态 1启用
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase价格监管规则停用(HttpRunner):

    config = Config("价格监管规则停用").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "ruleId": 1,
            "status": 1,
        })

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-op-api/goods/priceRule/$ruleId/stop/$status")
            .post(
                "/ppy-op-api/goods/priceRule/$ruleId/stop/$status"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "2",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase价格监管规则停用().test_start()
