# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase创建毛利锁规则(HttpRunner):

    config = Config("创建毛利锁规则").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "startTime": "${hapentime(1)}"+":00",
            "endTime": "${hapentime(100)}"+":00",
            "ruleName": "毛利锁",
        })

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-op-api/goods/priceRule")
            .post("/ppy-op-api/goods/priceRule")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "500",
                    "sessionId": "$session",
                    "Sec-Fetch-Dest": "empty",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "traIds": [296, 298],
                    "priceDimensionType": 3,
                    "ruleName": "$ruleName",
                    "cityCode": "100001",
                    "relationIds": [
                        1133,
                        1136,
                        1139,
                        1142,
                        1145,
                        1148,
                        1151,
                        1154,
                        1157,
                        1160,
                        1163,
                        1166,
                        1169,
                        1172,
                        1175,
                        1178,
                        1181,
                        1184,
                        1187,
                        1190,
                        1193,
                        1196,
                        1199,
                        1202,
                        1205,
                        1208,
                        1211,
                        1214,
                        1217,
                        1220,
                        1223,
                        1226,
                        1229,
                        1232,
                        1235,
                        1238,
                        1241,
                        1244,
                        1247,
                        1250,
                        5289,
                        5290,
                        5291,
                        5292,
                        5293,
                    ],
                    "sellPriceType": 1,
                    "maxRate": 8,
                    "date": ["2020-10-21 00:00:00", "2020-11-30 23:59:59"],
                    "handleType": 1,
                    "startTime": "$startTime",
                    "endTime": "$endTime",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase创建毛利锁规则().test_start()
