# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase删除前台类目(HttpRunner):

    config = Config("删除前台类目").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "receptionCategoryId": 150,
        })

    teststeps = [
        Step(
            RunRequest("/test_t/mall/receptionCategory/$receptionCategoryId")
            .delete("/mall/receptionCategory/$receptionCategoryId")
            .with_headers(
                **{
                    "sessionId": "$session",
                    "systemCode": "yypp",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase删除前台类目().test_start()
