# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        在售商品搜索校验，输入搜索条件，验证搜索结果是否正确
    输入参数：
        无
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env

class TestCase在售商品查询(HttpRunner):

    config = Config("在售商品查询").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "queryValue": "",

        }).export(*["goodsId", "id", "disabled"])

    teststeps = [
        Step(
            RunRequest("/mall/sell/list")
            .post("/mall/sell/list")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "257",
                    "Accept": "application/json, text/plain, */*",
                    "Sec-Fetch-Dest": "empty",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "traId": 11,
                    "sellOut": "",
                    "statusList": [],
                    "tabLabelId": "",
                    "queryType": "goodsId",
                    "queryValue": "$queryValue",
                    "pageNum": 1,
                    "pageSize": 10,
                    "shelfState": 0,
                    "goodsType": "1",
                    "backstageCategoryId": 1133
                }
            ).extract()
            .with_jmespath("body.body.pageData[0].goodsId", "goodsId")
            .with_jmespath("body.body.pageData[0].id", "id")
            .with_jmespath("body.body.pageData[0].disabled", "disabled")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase在售商品查询().test_start()
# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: null",
# 	"timestamp": 1603767187,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"pageNum": 1,
# 		"pageSize": 10,
# 		"pageCount": 1,
# 		"totalSize": 1,
# 		"pageData": [{
# 			"id": 224983,
# 			"goodsId": 53095,
# 			"goodsName": "香约芒果布丁奶茶76g*30杯",
# 			"batchNo": null,
# 			"zoneCode": null,
# 			"zoneName": null,
# 			"topIndex": null,
# 			"startNum": 1,
# 			"maxNum": 50,
# 			"storeNum": 100,
# 			"initStock": 100,
# 			"safeStock": 0,
# 			"lockStock": 0,
# 			"zeroPrice": 120.00,
# 			"showScatteredPrice": 122.00,
# 			"currentNum": 1,
# 			"currentPrice": null,
# 			"successNum": null,
# 			"successPrice": 120.00,
# 			"disabled": 0,
# 			"specification": "76g*30杯/箱",
# 			"pic": 1,
# 			"picList": ["https://images.alpha.pinpianyi.cn/images/common/929a8a47fd62476385ded120884ac351.jpg"],
# 			"brand": null,
# 			"spellSellOut": false,
# 			"rate": null,
# 			"sortIndex": null,
# 			"surpriseNum": null,
# 			"traName": "滨江-商圈",
# 			"traId": 11,
# 			"surpriseId": null,
# 			"stockLink": true
# 		}]
# 	}
# }
