# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        无
    输入参数：
        specificationDesc  ：商品规格描述
        barCode: 商品条码ID
        "brandId": 品牌ID
        name ：商品名称
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import random


class TestCase新增商品申请单(HttpRunner):

    config = Config("新增商品申请单").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "barCode": random.randint(111111111, 999999999),
            "specificationDesc": random.randint(111, 999),
            "brandId": 4,
            "name": "这个商品好"
        })

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-op-api/goods/apply/add")
            .post("/ppy-op-api/goods/apply/add")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "829",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "id": None,
                    "brandId": "$brandId",
                    "brand": 4,
                    "single": 1,
                    "dan": 1,
                    "name": "$name",
                    "specificationDesc": "$specificationDesc",
                    "gatherUserName": "郑和",
                    "specialty": "0",
                    "isImport": "0",
                    "storageMethod": "1",
                    "guaranteePeriodUnit": "天",
                    "mainImageUrl": "http://images.alpha.pinpianyi.cn/images/library/05a457df710847b8b925f70bf3994f25-800*800..png",
                    "detailImageUrls": [
                        "http://images.alpha.pinpianyi.cn/images/library/44aa7b1d44384a5894fe00d665d1fea5-800*800..png"
                    ],
                    "goodsCapacity": 1,
                    "theoryVolume": 4,
                    "weight": 22,
                    "scatteredPrice": 16.8,
                    "retailPrice": 18,
                    "guaranteePeriod": 900,
                    "goodsCapacityUnit": "ml",
                    "goodsPacketUnit": "箱",
                    "gatherUserId": 3328,
                    "manufacturer": "1",
                    "backstageCategoryId": 1133,
                    "logisticsPurchaseNum": 1,
                    "lwh": "2x1x2",
                    "barCodeImageUrl": "http://images.alpha.pinpianyi.cn/images/goods/barCodea90d67871248498bac2007990d6efb2c.png",
                    "barCode": "$barCode",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            .assert_equal("body.body", True)
        ),
    ]


if __name__ == "__main__":
    TestCase新增商品申请单().test_start()
