# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        查询某个父类下的子类目
    输入参数：
        "parentId": 后台父类目编号，为null表示查询第一级类目
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查询某个父类下的子类目(HttpRunner):

    config = Config("查询某个父类下的子类目").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "parentId": ''
        }).export(*["backstageCategoryId"])

    teststeps = [
        Step(
            RunRequest("/test_t/ppy-op-api/backstageCategory/queryCategorysByParentId")
            .post(
                "/ppy-op-api/backstageCategory/queryCategorysByParentId"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "17",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json({"parentId": "$parentId"})
            .extract()
            .with_jmespath("body.body[-1].id", "backstageCategoryId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase查询某个父类下的子类目().test_start()
"""
response:
body     : {
    "statusCode": 2000,
    "msg": null,
    "traceMsg": "traceId: 1603272846122",
    "timestamp": 1603272846,
    "signType": null,
    "sign": null,
    "body": [
        {
            "id": 5296,
            "backstageCategoryName": "测试看看11",
            "parentId": 5294,
            "hasChildFlag": false,
            "depth": 2,
            "treePaths": "5294",
            "treePathsName": "测试看看>测试看看11",
            "finalNode": null,
            "orderClassifyDesc": null,
            "expire": null,
            "backExpire": null,
            "expireDisable": null,
            "hotSaleRatio": "0.00%",
            "percent": "0.00%",
            "expireEdit": false,
            "backExpireEdit": false
        }
    ]
}
"""