# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        分页标签查询
    输入参数：
        "categoryCode": 分类编码
        "pageNum": 页码
        "pageSize": 分页大小
        "name": 标签名称
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase分页标签查询(HttpRunner):

    config = Config("分页标签查询").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "categoryCode": "002",
            "pageNum": 1,
            "pageSize": 100,
            "name": ""
        })

    teststeps = [
        Step(
            RunRequest("/ppy-op-api/label/query/page")
            .post("/ppy-op-api/label/query/page")
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "59",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {"categoryCode": "$categoryCode", "pageNum": "$pageNum", "pageSize": "$pageSize", "name": "$name"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase分页标签查询().test_start()
# response
# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: 1605087687601",
# 	"timestamp": 1605087687,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"pageNum": 1,
# 		"pageSize": 100,
# 		"pageCount": 1,
# 		"totalSize": 25,
# 		"pageData": [{
# 			"id": 65,
# 			"name": "上门收款",
# 			"code": "2096",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:14"
# 		}, {
# 			"id": 66,
# 			"name": "换货",
# 			"code": "2459",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:52"
# 		}, {
# 			"id": 67,
# 			"name": "退货",
# 			"code": "3828",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:53"
# 		}, {
# 			"id": 68,
# 			"name": "拒收",
# 			"code": "6137",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:53"
# 		}, {
# 			"id": 69,
# 			"name": "缺货",
# 			"code": "1460",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:53"
# 		}, {
# 			"id": 70,
# 			"name": "延迟配送",
# 			"code": "9077",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:53"
# 		}, {
# 			"id": 71,
# 			"name": "未结算",
# 			"code": "4425",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2018-01-26 17:53"
# 		}, {
# 			"id": 76,
# 			"name": "无需退款",
# 			"code": "5390",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-02-10 16:26"
# 		}, {
# 			"id": 77,
# 			"name": "需退款",
# 			"code": "9043",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-02-10 16:30"
# 		}, {
# 			"id": 79,
# 			"name": "结算异常",
# 			"code": "1645",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2018-02-24 15:27"
# 		}, {
# 			"id": 80,
# 			"name": "坏账订单",
# 			"code": "2149",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-02-26 18:21"
# 		}, {
# 			"id": 98,
# 			"name": "特惠组合",
# 			"code": "3500",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": false,
# 			"createTime": "2018-09-28 00:57"
# 		}, {
# 			"id": 514,
# 			"name": "专区998半日达",
# 			"code": "1946",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-04-20 10:58"
# 		}, {
# 			"id": 517,
# 			"name": "专区9888专配",
# 			"code": "8646",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-04-20 10:58"
# 		}, {
# 			"id": 616,
# 			"name": "预售",
# 			"code": "9089",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-05-19 14:44"
# 		}, {
# 			"id": 694,
# 			"name": "拼易购",
# 			"code": "4145",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-06-12 15:46"
# 		}, {
# 			"id": 706,
# 			"name": "延迟-订单量少",
# 			"code": "2058",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-06-22 11:28"
# 		}, {
# 			"id": 709,
# 			"name": "延迟-运力不足",
# 			"code": "1023",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-06-22 11:28"
# 		}, {
# 			"id": 712,
# 			"name": "延迟-用户要求",
# 			"code": "3466",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-06-22 11:29"
# 		}, {
# 			"id": 718,
# 			"name": "延迟-供应商问题",
# 			"code": "7955",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-06-24 18:40"
# 		}, {
# 			"id": 721,
# 			"name": "延迟-系统异常",
# 			"code": "9693",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-06-24 18:40"
# 		}, {
# 			"id": 724,
# 			"name": "【生产日期：2019年12月】",
# 			"code": "7685",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": true,
# 			"createTime": "2020-06-27 11:54"
# 		}, {
# 			"id": 826,
# 			"name": "不配礼品袋",
# 			"code": "9776",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 1,
# 			"frontEndShow": true,
# 			"createTime": "2020-08-23 10:47"
# 		}, {
# 			"id": 838,
# 			"name": "水饮分拨",
# 			"code": "2372",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-08-25 18:44"
# 		}, {
# 			"id": 955,
# 			"name": "hot",
# 			"code": "1759",
# 			"categoryCode": "002",
# 			"categoryName": "订单标签",
# 			"disabled": 0,
# 			"frontEndShow": false,
# 			"createTime": "2020-09-21 19:41"
# 		}]
# 	}
# }