# NOTE: Generated By HttpRunner v3.1.4
"""
    概要：
        匹配运力
    输入参数：
        "requestList":车辆数据
        "tempDistributeId": 调用运力匹配返回返回
        "userNumLimit":
        "type":
        "openSplit":
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase匹配运力(HttpRunner):

    config = Config("匹配运力").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "requestList": [
                {
                    "id": "1218006391944421304",
                    "batchOn": "1218006381942621182",
                    "vehicleType": 11,
                    "vehicleName": "小面包",
                    "recommendNum": 0,
                    "actualNum": 0,
                    "logisticsArea": "3310001",
                    "logisticsName": "杭州北区",
                },
                {
                    "actualNum": 0,
                    "batchOn": "1218006381942621182",
                    "id": "1218006391944421306",
                    "logisticsArea": "3310001",
                    "logisticsName": "杭州北区",
                    "recommendNum": 0,
                    "vehicleName": "金杯",
                    "vehicleType": 12,
                },
            ],
            "tempDistributeId": None,
            "userNumLimit": 10,
            "type": 1,
            "openSplit": False,
        }).export(*["tempDistributeId", "virtualTransportationBaseVOList"])

    teststeps = [
        Step(
            RunRequest("/ppy-op-api/transCapacitys/execute/match")
            .post(
                "/ppy-op-api/transCapacitys/execute/match"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "2006",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "requestList": "$requestList",
                    "tempDistributeId": "$tempDistributeId",
                    "userNumLimit": "$userNumLimit",
                    "type": "$type",
                    "openSplit": "$openSplit",
                }
            ).extract()
            .with_jmespath("body.body.virtualTransportationBaseVOList", "virtualTransportationBaseVOList")
            .with_jmespath("body.body.tempDistributeId", "tempDistributeId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase匹配运力().test_start()
# response:
# {
# 	"statusCode": 2000,
# 	"msg": null,
# 	"traceMsg": "traceId: 1605000646229",
# 	"timestamp": 1605000651,
# 	"signType": null,
# 	"sign": null,
# 	"body": {
# 		"tempDistributeId": "1218006511503481926",
# 		"virtualTransportationBaseVOList": [{
# 			"virtualTransportationId": "1218006511503481564",
# 			"uuid": "1218006511503481935"
# 		}, {
# 			"virtualTransportationId": "1218006511503481573",
# 			"uuid": "1218006511503481940"
# 		}, {
# 			"virtualTransportationId": "1218006511503481577",
# 			"uuid": "1218006511503481942"
# 		}, {
# 			"virtualTransportationId": "1218006511503481584",
# 			"uuid": "1218006511503481951"
# 		}, {
# 			"virtualTransportationId": "1218006511503481588",
# 			"uuid": "1218006511503481960"
# 		}, {
# 			"virtualTransportationId": "1218006511503481591",
# 			"uuid": "1218006511503481964"
# 		}, {
# 			"virtualTransportationId": "1218006511503491698",
# 			"uuid": "1218006511503491573"
# 		}, {
# 			"virtualTransportationId": "1218006511503491706",
# 			"uuid": "1218006511503491580"
# 		}]
# 	}
# }