# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        根据车型查看司机信息，返回司机列表
    输入参数：
        "virtualTransportationId": 虚拟运单ID,
        "driverId": 司机ID,
        "plannedStartTime": 计划配送时间
        "cityCode": 城市编码,

    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase单个生成运单(HttpRunner):

    config = Config("单个生成运单").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "cityCode": "330100",
            "driverId": 68,
            "plannedStartTime": "2020-8-11 11:00",
            "virtualTransportationId": "1139128741300791517",
        })

    teststeps = [
        Step(
            RunRequest("单个生成运单")
            .post(
                "/logis/mng/transportationOrder/generateTransOrderForOne"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "120",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "cityCode": "$cityCode",
                    "driverId": "$driverId",
                    "plannedStartTime": "$plannedStartTime",
                    "virtualTransportationId": "$virtualTransportationId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase单个生成运单().test_start()

"""
request:
{
	"cityCode": "330100",
	"driverId": 68,
	"plannedStartTime": "2020-8-11 11:00",
	"virtualTransportationId": "1139128741300791517"
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597113376628",
	"timestamp": 1597113378,
	"signType": null,
	"sign": null,
	"body": true
}

"""