# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        根据车型查看司机信息，返回司机列表
    输入参数：
        "cityCode": 城市编码,
        "orderIdList": 需要修改的订单信息",
        "vehicleId": 车型ID,
    输出参数：
        "tempDistributeId":临时派单ID
        "virtualTransportationId":虚拟运单ID
        "uuid":uuid
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase新增车辆订单信息(HttpRunner):
    config = Config("新增车辆订单信息").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "cityCode": "330100",
            "orderNo": "2020081016494811212863-2",
            "vehicleId": 12,
        }).export(*["tempDistributeId", "virtualTransportationId", "uuid"])

    teststeps = [
        Step(
            RunRequest("新增车辆订单信息")
                .post("/logis/mng/virtual/addCarOrderInfo")
                .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "103",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
                .with_json(
                {
                    "cityCode": "$cityCode",
                    "orderIdList": ["$orderNo"],
                    "tempDistributeId": None,
                    "vehicleId": "$vehicleId",
                }
            ).extract()
                .with_jmespath("body.body.virtualTransportationBaseVOList[0].virtualTransportationId",
                               "virtualTransportationId")
                .with_jmespath("body.body.virtualTransportationBaseVOList[0].uuid",
                               "uuid")
                .with_jmespath("body.body.tempDistributeId", "tempDistributeId")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase新增车辆订单信息().test_start()

"""
request:
{
	"cityCode": "330100",
	"orderIdList": ["2020081016494811212863-2"],
	"tempDistributeId": null,
	"vehicleId": 12
}

response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597114249669",
	"timestamp": 1597114250,
	"signType": null,
	"sign": null,
	"body": {
		"tempDistributeId": "1139165801307051951",
		"virtualTransportationBaseVOList": [{
			"virtualTransportationId": "1139165801307051544",
			"uuid": "329438"
		}]
	}
}
"""
