# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        查询路径规划计算状态
    输入参数：
        "virtualTransportationBaseVOList":虚拟订单编号列表
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase查询路径规划计算状态(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "virtualTransportationBaseVOList": ""
        })

    teststeps = [
        Step(
            RunRequest("/logis/mng/virtual/queryPathPlanningStatus")
            .post(
                "/logis/mng/virtual/queryPathPlanningStatus"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "103",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "virtualTransportationBaseVOList": "$virtualTransportationBaseVOList"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            ),
    ]


if __name__ == "__main__":
    TestCase查询路径规划计算状态().test_start()

"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597110543720",
	"timestamp": 1597110543,
	"signType": null,
	"sign": null,
	"body": {
		"calculateStatus": false
	}
}
"""

