# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        查询待派订单列表
    输入参数：
        "orderNo": 订单号,
        "chooseType": 选择类型 0所有 1店铺 2供应商
        "shopName": 店铺名称
        "shopPhone": 店铺联系电话
        "supplierName": 供应商名称
        "carrierName": 承运商名称
        "tempDistributeId": 临时派单ID
        "zoneCodes": 区域代码
        "shopTypeList": 店铺类型
        "orderClassify": 订单分类，值为1-A,2-B
        "originalOrderClassify": 确认时间 — 开始
        "endConfirmTime": 确认时间 — 结束
        "startConfirmTime": "",
        "labelCodeList": None,
    输出参数：
        无
    前置接口：
        用户登陆
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import env


class TestCase查询待派订单列表(HttpRunner):

    config = Config("查询待派订单列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "yyht",
            "session": "${getSession($business)}",
            "orderNo": "",
            "chooseType": 1,
            "shopName": None,
            "shopPhone": None,
            "supplierName": None,
            "carrierName": None,
            "tempDistributeId": None,
            "zoneCodes": ["3310001"],
            "shopTypeList": None,
            "orderClassify": "",
            "originalOrderClassify": "",
            "startConfirmTime": "2020-11-09 16:00:00",
            "endConfirmTime": "2020-11-10 16:00:00",
            "labelCodeList": None,
        }).export(*["orders"])

    teststeps = [
        Step(
            RunRequest("/logis/mng/virtual/queryDistributeOrder")
            .post(
                "/logis/mng/virtual/queryDistributeOrder"
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "338",
                    "Accept": "application/json, text/plain, */*",
                    "key": "",
                    "sessionId": "$session",
                    "Content-Type": "application/json",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .with_json(
                {
                    "base": {"cityCode": env.cityCode},
                    "chooseType": "$chooseType",
                    "orderNo": "$orderNo",
                    "shopName": "$shopName",
                    "shopPhone": "$shopPhone",
                    "supplierName": "$supplierName",
                    "carrierName": "$carrierName",
                    "tempDistributeId": "$tempDistributeId",
                    "zoneCodes": "$zoneCodes",
                    "shopTypeList": "$shopTypeList",
                    "orderClassify": "$orderClassify",
                    "originalOrderClassify": "$originalOrderClassify",
                    "startConfirmTime": "$startConfirmTime",
                    "endConfirmTime": "$endConfirmTime",
                    "labelCodeList": "$labelCodeList",
                }
            ).extract()
            .with_jmespath("body.body.orders", "orders")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
            ),
    ]


if __name__ == "__main__":
    TestCase查询待派订单列表().test_start()

"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1597109808946",
	"timestamp": 1597109809,
	"signType": null,
	"sign": null,
	"body": {
		"volumeTotal": "0.1200",
		"goodsTotal": 10,
		"total": 1,
		"orders": [{
			"orderId": "2020081021034011214556",
			"shopId": 322022,
			"shopName": "左邻右舍5115店",
			"weight": 80.0,
			"volume": "0.1200",
			"typeAmount": 1,
			"goodsTypeAmount": 1,
			"totalAmount": 10,
			"shopLongitude": null,
			"shopBdLon": "120.299770421791140000",
			"shopBdLat": "30.179018551539150000",
			"shopAddress": "杭州市市萧山区 北干街道 杭州萧山万丰五金机电市场105号 左邻右舍便利店",
			"supplierId": 9,
			"supplierName": "拼便宜供应链(自备仓)",
			"supplierLongitude": "120.31327020160872",
			"supplierLatitude": "30.211272345386675",
			"supplierAddress": "西兴",
			"hasDistribute": 0,
			"streetCode": "330109002",
			"zoneCode": "3310003",
			"zoneName": "城南-物流",
			"firstDelivery": 0
		}]
	}
}
"""