# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        根据订单号，查看人工待派单系统待派单列表
    输入参数：
        "orderNo":订单号
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase



class TestCase人工待派单系统待派单列表(HttpRunner):

    config = Config("人工待派单系统待派单列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "orderNo": "2020082610413214718486",
        })

    teststeps = [
        Step(
            RunRequest("/alpha_t/ppy-op-api/distributes/waitingdistribute/list")
            .get(
                "/ppy-op-api/distributes/waitingdistribute/list"
            )
            .with_params(
                **{
                    "labelCodes": "",
                    "cStartTime": "",
                    "cEndTime": "",
                    "pageNum": "1",
                    "pageSize": "10",
                    "sort": "true",
                    "currentBranch": "3",
                    "retry": "0",
                    "orderNo": "$orderNo",
                }
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase人工待派单系统待派单列表().test_start()

"""
response:
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1598407456704",
	"timestamp": 1598407456,
	"signType": null,
	"sign": null,
	"body": {
		"pageNum": 1,
		"pageSize": 10,
		"pageCount": 1,
		"totalSize": 1,
		"pageData": [{
			"orderCash": 787.0,
			"orderNo": "2020082610413214718486",
			"markId": false,
			"payTime": "2020-08-26 10:02:44",
			"estimateArrivedTime": "2020-08-27",
			"shopName": "家园超市",
			"orderStatus": "20",
			"traId": 104,
			"spellZoneName": "城南-物流",
			"isWaitingPay": false,
			"streetName": "新街镇",
			"payType": "在线支付",
			"createTime": "2020-08-26 10:02:44",
			"shopLabel": "普通会员VIP1",
			"dmZoneName": "萧山区",
			"shopType": "00",
			"status": "待派单",
			"toWaitingPayTime": null,
			"userId": 324668,
			"mallTraName": "萧山-商圈",
			"labelName": null,
			"orderClassifyText": "B品类",
			"distributeTime": "2020-08-26 10:04:14",
			"failReason": "系统异常",
			"failType": 2
		}]
	}
}
"""