# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        人工拆单页面订单详情
    输入参数：
        "orderNo":订单号
    输出参数：
        "goodsId":商品id
        "goodsNum":商品数量
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase人工拆单页面订单详情(HttpRunner):

    config = Config("人工拆单页面订单详情").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "orderNo": "2020082610413214718486"
        }).export(*["goodsId", "goodsNum"])

    teststeps = [
        Step(
            RunRequest("/alpha_t/ppy-op-api/distributes/dismantleDetail")
            .get(
                "/ppy-op-api/distributes/dismantleDetail"
            )
            .with_params(**{"orderNo": "$orderNo"})
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            ).extract()
            .with_jmespath("body.body.goodsList[0].goodsId","goodsId")
            .with_jmespath("body.body.goodsList[0].orderNum", "goodsNum")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase人工拆单页面订单详情().test_start()

"""
{
	"statusCode": 2000,
	"msg": null,
	"traceMsg": "traceId: 1598407932052",
	"timestamp": 1598407932,
	"signType": null,
	"sign": null,
	"body": {
		"orderNo": "2020082610413214718486-0",
		"zoneName": "城南-物流",
		"address": "建设四路与香樟路交叉口家园超市",
		"shopName": "家园超市",
		"contactName": "胡琴",
		"contactPhone": "18757128156",
		"logisTraCode": null,
		"goodsList": [{
			"goodsId": 6565,
			"goodsName": "喜之郎黄桃+蜜桃果肉果冻 200g*24盒",
			"goodsSpecification": "200g*24盒/箱",
			"pic": "images/face/GOODS_6565_36725510.jpg",
			"orderAmount": "787.00",
			"orderNum": 10
		}]
	}
}
"""