# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        人工派单
    输入参数：
        "goodId": 商品id
        "supplierId": 供应商id
        "goodsNum": 派单数量
        "storageId": 仓库ID
        "virtualStorageId": 虚拟仓库ID
        "orderNo": 订单号
    输出参数：
        无
    前置接口：
        无
"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase人工派单(HttpRunner):
    config = Config("人工派单").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session": "",
            "goodsId": 6565,
            "supplierId": 3509,
            "goodsNum": 10,
            "storageId": "1771",
            "virtualStorageId": "1972",
            "orderNo": "2020082811431419913001",
        })

    teststeps = [
        Step(
            RunRequest("/alpha_t/ppy-op-api/distributes/manual")
                .post("/ppy-op-api/distributes/manual")
                .with_headers(
                **{
                    "Connection": "keep-alive",
                    "Content-Length": "137",
                    "sessionId": "$session",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
                    "systemCode": "yypp",
                    "Content-Type": "application/json",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            )
                .with_json(
                {
                    "goodsInfo": [
                        {
                            "goodId": "$goodsId",
                            "supplierId": "$supplierId",
                            "goodsNum": "$goodsNum",
                            "storageId": "$storageId",
                            "virtualStorageId": "$virtualStorageId",
                        }
                    ],
                    "orderNo": "$orderNo",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase人工派单().test_start()
