# NOTE: Generated By HttpRunner v3.1.3
"""
    概要：
        全部订单列表接口，根据输入的订单号查询订单
    输入参数：
        "orderNo": 订单号
    输出参数：
        无
    前置接口：
        无
"""


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase



class TestCase全部订单列表(HttpRunner):

    config = Config("全部订单列表").verify(False).base_url("${testEnv($business)}").variables(
        **{
            "business": "",
            "session_yyht": "",
            "orderNo": "2020081315332711613328",
        }).export(*["orderList"])

    teststeps = [
        Step(
            RunRequest("/dev2_t/ppy-op-api/order/queryAllOrders")
            .get("/ppy-op-api/order/queryAllOrders")
            .with_params(
                **{
                    "isPay": "",
                    "payType": "",
                    "status": "",
                    "queryType": "",
                    "cloudType": "",
                    "labelCode": "",
                    "orderSource": "",
                    "backGoodsType": "",
                    "settleStatus": "",
                    "spellZoneCode": "",
                    "logisticsStatus": "",
                    "isInsufficient": "",
                    "orderClassify": "",
                    "orderNo": "$orderNo",
                    "pageNum": "1",
                    "pageSize": "25",
                    "sort": "true",
                }
            )
            .with_headers(
                **{
                    "Connection": "keep-alive",
                    "sessionId": "$session_yyht",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
                    "systemCode": "yypp",
                    "Accept": "*/*",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7",
                }
            ).extract().with_jmespath("body.body.pageData","orderList")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.statusCode", 2000)
        ),
    ]


if __name__ == "__main__":
    TestCase全部订单列表().test_start()
